// generated 2003/9/3 1:40:11 GMT by tamer@katakis.(none)
// using glademm V2.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /scratch/studierstube/studierstube/src/apps/vacuum/gtk/vacuum.glade
// for gtk 2.2.1 and gtkmm 2.2.5
//
// Please modify the corresponding derived classes in .//about_dialog.hh and.//about_dialog.cc

#ifndef _ABOUT_DIALOG_GLADE_HH
#  define _ABOUT_DIALOG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>

class about_dialog_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        
        about_dialog_glade();
        
        ~about_dialog_glade();
};
#endif
