// generated 2003/9/3 1:40:11 GMT by tamer@katakis.(none)
// using glademm V2.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /scratch/studierstube/studierstube/src/apps/vacuum/gtk/vacuum.glade
// for gtk 2.2.1 and gtkmm 2.2.5
//
// Please modify the corresponding derived classes in .//fileselection.hh and.//fileselection.cc

#ifndef _FILESELECTION_GLADE_HH
#  define _FILESELECTION_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/fileselection.h>

class fileselection_glade : public Gtk::FileSelection
{  
        
        GlademmData *gmm_data;
protected:
        
        fileselection_glade();
        
        ~fileselection_glade();
private:
        virtual void on_fs_ok_button_clicked() = 0;
};
#endif
