// generated 2003/9/3 2:02:24 GMT by tamer@katakis.(none)
// using glademm V2.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /scratch/studierstube/studierstube/src/apps/vacuum/gtk/vacuum.glade
// for gtk 2.2.1 and gtkmm 2.2.5
//
// Please modify the corresponding derived classes in .//fileselection.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include "fileselection_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>

fileselection_glade::fileselection_glade(
) : Gtk::FileSelection("Select Volume")
{  
   
   Gtk::FileSelection *fileselection = this;
   gmm_data = new GlademmData(get_accel_group());
   fileselection->get_cancel_button()->set_flags(Gtk::CAN_FOCUS);
   fileselection->get_cancel_button()->set_relief(Gtk::RELIEF_NORMAL);
   fileselection->get_ok_button()->set_flags(Gtk::CAN_FOCUS);
   fileselection->get_ok_button()->set_relief(Gtk::RELIEF_NORMAL);
   fileselection->set_border_width(10);
   fileselection->set_title("Select Volume");
   fileselection->set_modal(true);
   fileselection->property_window_position().set_value(Gtk::WIN_POS_NONE);
   fileselection->set_resizable(true);
   fileselection->property_destroy_with_parent().set_value(true);
   fileselection->hide_fileop_buttons();
   fileselection->show();
   fileselection->get_cancel_button()->signal_clicked().connect(SigC::slot(*this, &Gtk::Widget::hide));
   fileselection->get_ok_button()->signal_clicked().connect(SigC::slot(*this, &fileselection_glade::on_fs_ok_button_clicked));
}

fileselection_glade::~fileselection_glade()
{  delete gmm_data;
}
