// generated 2003/9/11 18:15:48 GMT by tamer@katakis.(none)
// using glademm V2.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /scratch/studierstube/studierstube/src/apps/vacuum/gtk/vacuum.glade
// for gtk 2.2.1 and gtkmm 2.2.5
//
// Please modify the corresponding derived classes in .//window1.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include "window1_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/colorselection.h>

window1_glade::window1_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *window1 = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::ColorSelection *colorselection1 = Gtk::manage(new class Gtk::ColorSelection());
   window1->set_title("window1");
   window1->set_modal(false);
   window1->property_window_position().set_value(Gtk::WIN_POS_NONE);
   window1->set_resizable(true);
   window1->property_destroy_with_parent().set_value(false);
   window1->add(*colorselection1);
   colorselection1->show();
   window1->show();
}

window1_glade::~window1_glade()
{  delete gmm_data;
}
