#ifndef FEATURE_LIST_POOL_INCLUDED
#define FEATURE_LIST_POOL_INCLUDED

#include "feature_list.h"
#include "feature_pool.h"

typedef feature_list<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE,15> FEATURE_LIST_2D;
typedef feature_list<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE,28> FEATURE_LIST_3D;
typedef feature_list<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE,56> FEATURE_LIST_6D;

#define DEFINED_FEATURE_LIST_TYPE	FEATURE_LIST_2D

//----------------------------------------------------------------------------
#if DEFINED_FEATURE_LIST_TYPE==FEATURE_LIST_2D
void build_feature_list(FEATURE_LIST_2D &fl)
{
	feature<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE> f;
	
	f.define(FEATURE_STRAIGHTNESS,FEATURE_CALCULATE_STRAIGHTNESS,FEATURE_INITIALIZE_STRAIGHTNESS);
	fl.set(0,f);
    
	f.define(FEATURE_HEIGHT_WIDTH_RATIO,FEATURE_CALCULATE_HEIGHT_WIDTH_RATIO,FEATURE_INITIALIZE_HEIGHT_WIDTH_RATIO);
	fl.set(1,f);
    
	f.define(FEATURE_HEIGHT_WIDTH_RATIO_R45,FEATURE_CALCULATE_HEIGHT_WIDTH_RATIO_R45,FEATURE_INITIALIZE_HEIGHT_WIDTH_RATIO_R45);
	fl.set(2,f);
    
    f.define(FEATURE_RELATIVE_START_X,FEATURE_CALCULATE_RELATIVE_START_X,FEATURE_INITIALIZE_RELATIVE_START_X);
	fl.set(3,f);
    f.define(FEATURE_RELATIVE_START_Y,FEATURE_CALCULATE_RELATIVE_START_Y,FEATURE_INITIALIZE_RELATIVE_START_Y);
	fl.set(4,f);
    
	f.define(FEATURE_RELATIVE_END_X,FEATURE_CALCULATE_RELATIVE_END_X,FEATURE_INITIALIZE_RELATIVE_END_X);
	fl.set(5,f);
    f.define(FEATURE_RELATIVE_END_Y,FEATURE_CALCULATE_RELATIVE_END_Y,FEATURE_INITIALIZE_RELATIVE_END_Y);
	fl.set(6,f);
    
    f.define(FEATURE_HORIZONTAL_MOVEMENTS,FEATURE_CALCULATE_HORIZONTAL_MOVEMENTS,FEATURE_INITIALIZE_HORIZONTAL_MOVEMENTS);
	fl.set(7,f);
    f.define(FEATURE_VERTICAL_MOVEMENTS,FEATURE_CALCULATE_VERTICAL_MOVEMENTS,FEATURE_INITIALIZE_VERTICAL_MOVEMENTS);
	fl.set(8,f); 

    f.define(FEATURE_HORIZONTAL_MOVEMENTS_R45,FEATURE_CALCULATE_HORIZONTAL_MOVEMENTS_R45,FEATURE_INITIALIZE_HORIZONTAL_MOVEMENTS_R45);
	fl.set(9,f);
    f.define(FEATURE_VERTICAL_MOVEMENTS_R45,FEATURE_CALCULATE_VERTICAL_MOVEMENTS_R45,FEATURE_INITIALIZE_VERTICAL_MOVEMENTS_R45);
	fl.set(10,f);
    
    f.define(FEATURE_START_ANGLE_X_Y,FEATURE_CALCULATE_START_ANGLE_X_Y,FEATURE_INITIALIZE_START_ANGLE_X_Y);
	fl.set(11,f);
    
	f.define(FEATURE_END_ANGLE_X_Y,FEATURE_CALCULATE_END_ANGLE_X_Y,FEATURE_INITIALIZE_END_ANGLE_X_Y);
	fl.set(12,f);
    
    f.define(FEATURE_RELATIVE_CG_X,FEATURE_CALCULATE_RELATIVE_CG_X,FEATURE_INITIALIZE_RELATIVE_CG_X);
	fl.set(13,f);
    f.define(FEATURE_RELATIVE_CG_Y,FEATURE_CALCULATE_RELATIVE_CG_Y,FEATURE_INITIALIZE_RELATIVE_CG_Y);
	fl.set(14,f);  
	
}
#endif
//----------------------------------------------------------------------------
#if DEFINED_FEATURE_LIST_TYPE==FEATURE_LIST_3D
void build_feature_list(FEATURE_LIST_3D &fl)
{
	feature<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE> f;
	
	f.define(FEATURE_STRAIGHTNESS,FEATURE_CALCULATE_STRAIGHTNESS,FEATURE_INITIALIZE_STRAIGHTNESS);
	fl.set(0,f);
    
	f.define(FEATURE_HEIGHT_WIDTH_RATIO,FEATURE_CALCULATE_HEIGHT_WIDTH_RATIO,FEATURE_INITIALIZE_HEIGHT_WIDTH_RATIO);
	fl.set(1,f);
	f.define(FEATURE_HEIGHT_DEPTH_RATIO,FEATURE_CALCULATE_HEIGHT_DEPTH_RATIO,FEATURE_INITIALIZE_HEIGHT_DEPTH_RATIO);
	fl.set(2,f);
    f.define(FEATURE_DEPTH_WIDTH_RATIO,FEATURE_CALCULATE_DEPTH_WIDTH_RATIO,FEATURE_INITIALIZE_DEPTH_WIDTH_RATIO);
	fl.set(3,f);
    
	f.define(FEATURE_HEIGHT_WIDTH_RATIO_R45,FEATURE_CALCULATE_HEIGHT_WIDTH_RATIO_R45,FEATURE_INITIALIZE_HEIGHT_WIDTH_RATIO_R45);
	fl.set(4,f);
    f.define(FEATURE_HEIGHT_DEPTH_RATIO_R45,FEATURE_CALCULATE_HEIGHT_DEPTH_RATIO_R45,FEATURE_INITIALIZE_HEIGHT_DEPTH_RATIO_R45);
	fl.set(5,f);
    f.define(FEATURE_DEPTH_WIDTH_RATIO_R45,FEATURE_CALCULATE_DEPTH_WIDTH_RATIO_R45,FEATURE_INITIALIZE_DEPTH_WIDTH_RATIO_R45);
	fl.set(6,f);

    f.define(FEATURE_RELATIVE_START_X,FEATURE_CALCULATE_RELATIVE_START_X,FEATURE_INITIALIZE_RELATIVE_START_X);
	fl.set(7,f);
    f.define(FEATURE_RELATIVE_START_Y,FEATURE_CALCULATE_RELATIVE_START_Y,FEATURE_INITIALIZE_RELATIVE_START_Y);
	fl.set(8,f);
    f.define(FEATURE_RELATIVE_START_Z,FEATURE_CALCULATE_RELATIVE_START_Z,FEATURE_INITIALIZE_RELATIVE_START_Z);
	fl.set(9,f);
 
	f.define(FEATURE_RELATIVE_END_X,FEATURE_CALCULATE_RELATIVE_END_X,FEATURE_INITIALIZE_RELATIVE_END_X);
	fl.set(10,f);
    f.define(FEATURE_RELATIVE_END_Y,FEATURE_CALCULATE_RELATIVE_END_Y,FEATURE_INITIALIZE_RELATIVE_END_Y);
	fl.set(11,f);
    f.define(FEATURE_RELATIVE_END_Z,FEATURE_CALCULATE_RELATIVE_END_Z,FEATURE_INITIALIZE_RELATIVE_END_Z);
	fl.set(12,f);

    f.define(FEATURE_HORIZONTAL_MOVEMENTS,FEATURE_CALCULATE_HORIZONTAL_MOVEMENTS,FEATURE_INITIALIZE_HORIZONTAL_MOVEMENTS);
	fl.set(13,f);
    f.define(FEATURE_VERTICAL_MOVEMENTS,FEATURE_CALCULATE_VERTICAL_MOVEMENTS,FEATURE_INITIALIZE_VERTICAL_MOVEMENTS);
	fl.set(14,f);
    f.define(FEATURE_DEPTH_MOVEMENTS,FEATURE_CALCULATE_DEPTH_MOVEMENTS,FEATURE_INITIALIZE_DEPTH_MOVEMENTS);
	fl.set(15,f);


    f.define(FEATURE_HORIZONTAL_MOVEMENTS_R45,FEATURE_CALCULATE_HORIZONTAL_MOVEMENTS_R45,FEATURE_INITIALIZE_HORIZONTAL_MOVEMENTS_R45);
	fl.set(16,f);
    f.define(FEATURE_VERTICAL_MOVEMENTS_R45,FEATURE_CALCULATE_VERTICAL_MOVEMENTS_R45,FEATURE_INITIALIZE_VERTICAL_MOVEMENTS_R45);
	fl.set(17,f);
    f.define(FEATURE_DEPTH_MOVEMENTS_R45,FEATURE_CALCULATE_DEPTH_MOVEMENTS_R45,FEATURE_INITIALIZE_DEPTH_MOVEMENTS_R45);
	fl.set(18,f);

    f.define(FEATURE_START_ANGLE_X_Y,FEATURE_CALCULATE_START_ANGLE_X_Y,FEATURE_INITIALIZE_START_ANGLE_X_Y);
	fl.set(19,f);
    f.define(FEATURE_START_ANGLE_X_Z,FEATURE_CALCULATE_START_ANGLE_X_Z,FEATURE_INITIALIZE_START_ANGLE_X_Z);
	fl.set(20,f);
    f.define(FEATURE_START_ANGLE_Z_Y,FEATURE_CALCULATE_START_ANGLE_Z_Y,FEATURE_INITIALIZE_START_ANGLE_Z_Y);
	fl.set(21,f);

	f.define(FEATURE_END_ANGLE_X_Y,FEATURE_CALCULATE_END_ANGLE_X_Y,FEATURE_INITIALIZE_END_ANGLE_X_Y);
	fl.set(22,f);
    f.define(FEATURE_END_ANGLE_X_Z,FEATURE_CALCULATE_END_ANGLE_X_Z,FEATURE_INITIALIZE_END_ANGLE_X_Z);
	fl.set(23,f);
    f.define(FEATURE_END_ANGLE_Z_Y,FEATURE_CALCULATE_END_ANGLE_Z_Y,FEATURE_INITIALIZE_END_ANGLE_Z_Y);
	fl.set(24,f);

    f.define(FEATURE_RELATIVE_CG_X,FEATURE_CALCULATE_RELATIVE_CG_X,FEATURE_INITIALIZE_RELATIVE_CG_X);
	fl.set(25,f);
    f.define(FEATURE_RELATIVE_CG_Y,FEATURE_CALCULATE_RELATIVE_CG_Y,FEATURE_INITIALIZE_RELATIVE_CG_Y);
	fl.set(26,f);
    f.define(FEATURE_RELATIVE_CG_Z,FEATURE_CALCULATE_RELATIVE_CG_Z,FEATURE_INITIALIZE_RELATIVE_CG_Z);
	fl.set(27,f);
}
#endif
//----------------------------------------------------------------------------
#if DEFINED_FEATURE_LIST_TYPE==FEATURE_LIST_6D
void build_feature_list(FEATURE_LIST_6D &fl)
{
	feature<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE> f;
	
	f.define(FEATURE_STRAIGHTNESS,FEATURE_CALCULATE_STRAIGHTNESS,FEATURE_INITIALIZE_STRAIGHTNESS);
	fl.set(0,f);
    
	f.define(FEATURE_HEIGHT_WIDTH_RATIO,FEATURE_CALCULATE_HEIGHT_WIDTH_RATIO,FEATURE_INITIALIZE_HEIGHT_WIDTH_RATIO);
	fl.set(1,f);
	f.define(FEATURE_HEIGHT_DEPTH_RATIO,FEATURE_CALCULATE_HEIGHT_DEPTH_RATIO,FEATURE_INITIALIZE_HEIGHT_DEPTH_RATIO);
	fl.set(2,f);
    f.define(FEATURE_DEPTH_WIDTH_RATIO,FEATURE_CALCULATE_DEPTH_WIDTH_RATIO,FEATURE_INITIALIZE_DEPTH_WIDTH_RATIO);
	fl.set(3,f);
    
	f.define(FEATURE_HEIGHT_WIDTH_RATIO_R45,FEATURE_CALCULATE_HEIGHT_WIDTH_RATIO_R45,FEATURE_INITIALIZE_HEIGHT_WIDTH_RATIO_R45);
	fl.set(4,f);
    f.define(FEATURE_HEIGHT_DEPTH_RATIO_R45,FEATURE_CALCULATE_HEIGHT_DEPTH_RATIO_R45,FEATURE_INITIALIZE_HEIGHT_DEPTH_RATIO_R45);
	fl.set(5,f);
    f.define(FEATURE_DEPTH_WIDTH_RATIO_R45,FEATURE_CALCULATE_DEPTH_WIDTH_RATIO_R45,FEATURE_INITIALIZE_DEPTH_WIDTH_RATIO_R45);
	fl.set(6,f);

    f.define(FEATURE_RELATIVE_START_X,FEATURE_CALCULATE_RELATIVE_START_X,FEATURE_INITIALIZE_RELATIVE_START_X);
	fl.set(7,f);
    f.define(FEATURE_RELATIVE_START_Y,FEATURE_CALCULATE_RELATIVE_START_Y,FEATURE_INITIALIZE_RELATIVE_START_Y);
	fl.set(8,f);
    f.define(FEATURE_RELATIVE_START_Z,FEATURE_CALCULATE_RELATIVE_START_Z,FEATURE_INITIALIZE_RELATIVE_START_Z);
	fl.set(9,f);
 
	f.define(FEATURE_RELATIVE_END_X,FEATURE_CALCULATE_RELATIVE_END_X,FEATURE_INITIALIZE_RELATIVE_END_X);
	fl.set(10,f);
    f.define(FEATURE_RELATIVE_END_Y,FEATURE_CALCULATE_RELATIVE_END_Y,FEATURE_INITIALIZE_RELATIVE_END_Y);
	fl.set(11,f);
    f.define(FEATURE_RELATIVE_END_Z,FEATURE_CALCULATE_RELATIVE_END_Z,FEATURE_INITIALIZE_RELATIVE_END_Z);
	fl.set(12,f);

    f.define(FEATURE_HORIZONTAL_MOVEMENTS,FEATURE_CALCULATE_HORIZONTAL_MOVEMENTS,FEATURE_INITIALIZE_HORIZONTAL_MOVEMENTS);
	fl.set(13,f);
    f.define(FEATURE_VERTICAL_MOVEMENTS,FEATURE_CALCULATE_VERTICAL_MOVEMENTS,FEATURE_INITIALIZE_VERTICAL_MOVEMENTS);
	fl.set(14,f);
    f.define(FEATURE_DEPTH_MOVEMENTS,FEATURE_CALCULATE_DEPTH_MOVEMENTS,FEATURE_INITIALIZE_DEPTH_MOVEMENTS);
	fl.set(15,f);


    f.define(FEATURE_HORIZONTAL_MOVEMENTS_R45,FEATURE_CALCULATE_HORIZONTAL_MOVEMENTS_R45,FEATURE_INITIALIZE_HORIZONTAL_MOVEMENTS_R45);
	fl.set(16,f);
    f.define(FEATURE_VERTICAL_MOVEMENTS_R45,FEATURE_CALCULATE_VERTICAL_MOVEMENTS_R45,FEATURE_INITIALIZE_VERTICAL_MOVEMENTS_R45);
	fl.set(17,f);
    f.define(FEATURE_DEPTH_MOVEMENTS_R45,FEATURE_CALCULATE_DEPTH_MOVEMENTS_R45,FEATURE_INITIALIZE_DEPTH_MOVEMENTS_R45);
	fl.set(18,f);

    f.define(FEATURE_START_ANGLE_X_Y,FEATURE_CALCULATE_START_ANGLE_X_Y,FEATURE_INITIALIZE_START_ANGLE_X_Y);
	fl.set(19,f);
    f.define(FEATURE_START_ANGLE_X_Z,FEATURE_CALCULATE_START_ANGLE_X_Z,FEATURE_INITIALIZE_START_ANGLE_X_Z);
	fl.set(20,f);
    f.define(FEATURE_START_ANGLE_Z_Y,FEATURE_CALCULATE_START_ANGLE_Z_Y,FEATURE_INITIALIZE_START_ANGLE_Z_Y);
	fl.set(21,f);

	f.define(FEATURE_END_ANGLE_X_Y,FEATURE_CALCULATE_END_ANGLE_X_Y,FEATURE_INITIALIZE_END_ANGLE_X_Y);
	fl.set(22,f);
    f.define(FEATURE_END_ANGLE_X_Z,FEATURE_CALCULATE_END_ANGLE_X_Z,FEATURE_INITIALIZE_END_ANGLE_X_Z);
	fl.set(23,f);
    f.define(FEATURE_END_ANGLE_Z_Y,FEATURE_CALCULATE_END_ANGLE_Z_Y,FEATURE_INITIALIZE_END_ANGLE_Z_Y);
	fl.set(24,f);

    f.define(FEATURE_RELATIVE_CG_X,FEATURE_CALCULATE_RELATIVE_CG_X,FEATURE_INITIALIZE_RELATIVE_CG_X);
	fl.set(25,f);
    f.define(FEATURE_RELATIVE_CG_Y,FEATURE_CALCULATE_RELATIVE_CG_Y,FEATURE_INITIALIZE_RELATIVE_CG_Y);
	fl.set(26,f);
    f.define(FEATURE_RELATIVE_CG_Z,FEATURE_CALCULATE_RELATIVE_CG_Z,FEATURE_INITIALIZE_RELATIVE_CG_Z);
	fl.set(27,f);


	f.define(FEATURE_ORIENTATION_STRAIGHTNESS,FEATURE_CALCULATE_ORIENTATION_STRAIGHTNESS,FEATURE_INITIALIZE_ORIENTATION_STRAIGHTNESS);
	fl.set(28,f);
    
	f.define(FEATURE_ORIENTATION_HEIGHT_WIDTH_RATIO,FEATURE_CALCULATE_ORIENTATION_HEIGHT_WIDTH_RATIO,FEATURE_INITIALIZE_ORIENTATION_HEIGHT_WIDTH_RATIO);
	fl.set(29,f);
	f.define(FEATURE_ORIENTATION_HEIGHT_DEPTH_RATIO,FEATURE_CALCULATE_ORIENTATION_HEIGHT_DEPTH_RATIO,FEATURE_INITIALIZE_ORIENTATION_HEIGHT_DEPTH_RATIO);
	fl.set(30,f);
    f.define(FEATURE_ORIENTATION_DEPTH_WIDTH_RATIO,FEATURE_CALCULATE_ORIENTATION_DEPTH_WIDTH_RATIO,FEATURE_INITIALIZE_ORIENTATION_DEPTH_WIDTH_RATIO);
	fl.set(31,f);
    
	f.define(FEATURE_ORIENTATION_HEIGHT_WIDTH_RATIO_R45,FEATURE_CALCULATE_ORIENTATION_HEIGHT_WIDTH_RATIO_R45,FEATURE_INITIALIZE_ORIENTATION_HEIGHT_WIDTH_RATIO_R45);
	fl.set(32,f);
    f.define(FEATURE_ORIENTATION_HEIGHT_DEPTH_RATIO_R45,FEATURE_CALCULATE_ORIENTATION_HEIGHT_DEPTH_RATIO_R45,FEATURE_INITIALIZE_ORIENTATION_HEIGHT_DEPTH_RATIO_R45);
	fl.set(33,f);
    f.define(FEATURE_ORIENTATION_DEPTH_WIDTH_RATIO_R45,FEATURE_CALCULATE_ORIENTATION_DEPTH_WIDTH_RATIO_R45,FEATURE_INITIALIZE_ORIENTATION_DEPTH_WIDTH_RATIO_R45);
	fl.set(34,f);

    f.define(FEATURE_ORIENTATION_RELATIVE_START_AZIM,FEATURE_CALCULATE_ORIENTATION_RELATIVE_START_AZIM,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_START_AZIM);
	fl.set(35,f);
    f.define(FEATURE_ORIENTATION_RELATIVE_START_ELEV,FEATURE_CALCULATE_ORIENTATION_RELATIVE_START_ELEV,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_START_ELEV);
	fl.set(36,f);
    f.define(FEATURE_ORIENTATION_RELATIVE_START_ROLL,FEATURE_CALCULATE_ORIENTATION_RELATIVE_START_ROLL,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_START_ROLL);
	fl.set(37,f);
 
	f.define(FEATURE_ORIENTATION_RELATIVE_END_AZIM,FEATURE_CALCULATE_ORIENTATION_RELATIVE_END_AZIM,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_END_AZIM);
	fl.set(38,f);
    f.define(FEATURE_ORIENTATION_RELATIVE_END_ELEV,FEATURE_CALCULATE_ORIENTATION_RELATIVE_END_ELEV,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_END_ELEV);
	fl.set(39,f);
    f.define(FEATURE_ORIENTATION_RELATIVE_END_ROLL,FEATURE_CALCULATE_ORIENTATION_RELATIVE_END_ROLL,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_END_ROLL);
	fl.set(40,f);

    f.define(FEATURE_ORIENTATION_AZIMUTHAL_MOVEMENTS,FEATURE_CALCULATE_ORIENTATION_AZIMUTHAL_MOVEMENTS,FEATURE_INITIALIZE_ORIENTATION_AZIMUTHAL_MOVEMENTS);
	fl.set(41,f);
    f.define(FEATURE_ORIENTATION_ELEVATION_MOVEMENTS,FEATURE_CALCULATE_ORIENTATION_ELEVATION_MOVEMENTS,FEATURE_INITIALIZE_ORIENTATION_ELEVATION_MOVEMENTS);
	fl.set(42,f);
    f.define(FEATURE_ORIENTATION_ROLL_MOVEMENTS,FEATURE_CALCULATE_ORIENTATION_ROLL_MOVEMENTS,FEATURE_INITIALIZE_ORIENTATION_ROLL_MOVEMENTS);
	fl.set(43,f);


    f.define(FEATURE_ORIENTATION_AZIMUTHAL_MOVEMENTS_R45,FEATURE_CALCULATE_ORIENTATION_AZIMUTHAL_MOVEMENTS_R45,FEATURE_INITIALIZE_ORIENTATION_AZIMUTHAL_MOVEMENTS_R45);
	fl.set(44,f);
    f.define(FEATURE_ORIENTATION_ELEVATION_MOVEMENTS_R45,FEATURE_CALCULATE_ORIENTATION_ELEVATION_MOVEMENTS_R45,FEATURE_INITIALIZE_ORIENTATION_ELEVATION_MOVEMENTS_R45);
	fl.set(45,f);
    f.define(FEATURE_ORIENTATION_ROLL_MOVEMENTS_R45,FEATURE_CALCULATE_ORIENTATION_ROLL_MOVEMENTS_R45,FEATURE_INITIALIZE_ORIENTATION_ROLL_MOVEMENTS_R45);
	fl.set(46,f);

    f.define(FEATURE_ORIENTATION_START_ANGLE_AZIM_ELEV,FEATURE_CALCULATE_ORIENTATION_START_ANGLE_AZIM_ELEV,FEATURE_INITIALIZE_ORIENTATION_START_ANGLE_AZIM_ELEV);
	fl.set(47,f);
    f.define(FEATURE_ORIENTATION_START_ANGLE_AZIM_ROLL,FEATURE_CALCULATE_ORIENTATION_START_ANGLE_AZIM_ROLL,FEATURE_INITIALIZE_ORIENTATION_START_ANGLE_AZIM_ROLL);
	fl.set(48,f);
    f.define(FEATURE_ORIENTATION_START_ANGLE_ROLL_ELEV,FEATURE_CALCULATE_ORIENTATION_START_ANGLE_ROLL_ELEV,FEATURE_INITIALIZE_ORIENTATION_START_ANGLE_ROLL_ELEV);
	fl.set(49,f);

	f.define(FEATURE_ORIENTATION_END_ANGLE_AZIM_ELEV,FEATURE_CALCULATE_ORIENTATION_END_ANGLE_AZIM_ELEV,FEATURE_INITIALIZE_ORIENTATION_END_ANGLE_AZIM_ELEV);
	fl.set(50,f);
    f.define(FEATURE_ORIENTATION_END_ANGLE_AZIM_ROLL,FEATURE_CALCULATE_ORIENTATION_END_ANGLE_AZIM_ROLL,FEATURE_INITIALIZE_ORIENTATION_END_ANGLE_AZIM_ROLL);
	fl.set(51,f);
    f.define(FEATURE_ORIENTATION_END_ANGLE_ROLL_ELEV,FEATURE_CALCULATE_ORIENTATION_END_ANGLE_ROLL_ELEV,FEATURE_INITIALIZE_ORIENTATION_END_ANGLE_ROLL_ELEV);
	fl.set(52,f);

    f.define(FEATURE_ORIENTATION_RELATIVE_CG_AZIM,FEATURE_CALCULATE_ORIENTATION_RELATIVE_CG_AZIM,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_CG_AZIM);
	fl.set(53,f);
    f.define(FEATURE_ORIENTATION_RELATIVE_CG_ELEV,FEATURE_CALCULATE_ORIENTATION_RELATIVE_CG_ELEV,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_CG_ELEV);
	fl.set(54,f);
    f.define(FEATURE_ORIENTATION_RELATIVE_CG_ROLL,FEATURE_CALCULATE_ORIENTATION_RELATIVE_CG_ROLL,FEATURE_INITIALIZE_ORIENTATION_RELATIVE_CG_ROLL);
	fl.set(55,f);
}
#endif
//----------------------------------------------------------------------------

#endif

