#ifndef FEATURE_DEVIATION_POOL_INCLUDED
#define FEATURE_DEVIATION_POOL_INCLUDED

#include "feature_pool.h"
#include "property_list_pool.h"
#include "dependence_pool.h"

#define DEFINED_FEATURE_DEVIATION_TYPE float

//dependence level 0-----------------------------------------------------------
#define	FEATURE_DEVIATION_STRAIGHTNESS				0

#define FEATURE_DEVIATION_HEIGHT_WIDTH_RATIO		1
#define FEATURE_DEVIATION_HEIGHT_DEPTH_RATIO		2
#define FEATURE_DEVIATION_DEPTH_WIDTH_RATIO			3

#define FEATURE_DEVIATION_HEIGHT_WIDTH_RATIO_R45		4
#define FEATURE_DEVIATION_HEIGHT_DEPTH_RATIO_R45		5
#define FEATURE_DEVIATION_DEPTH_WIDTH_RATIO_R45			6

#define FEATURE_DEVIATION_RELATIVE_START_X				7
#define FEATURE_DEVIATION_RELATIVE_START_Y				8
#define FEATURE_DEVIATION_RELATIVE_START_Z				9

#define FEATURE_DEVIATION_RELATIVE_END_X				10
#define FEATURE_DEVIATION_RELATIVE_END_Y				11
#define FEATURE_DEVIATION_RELATIVE_END_Z				12

#define FEATURE_DEVIATION_HORIZONTAL_MOVEMENTS			13
#define FEATURE_DEVIATION_VERTICAL_MOVEMENTS			14
#define FEATURE_DEVIATION_DEPTH_MOVEMENTS				15

#define FEATURE_DEVIATION_HORIZONTAL_MOVEMENTS_R45		16
#define FEATURE_DEVIATION_VERTICAL_MOVEMENTS_R45		17
#define FEATURE_DEVIATION_DEPTH_MOVEMENTS_R45			18

#define FEATURE_DEVIATION_START_ANGLE_X_Y			19
#define FEATURE_DEVIATION_START_ANGLE_X_Z			20
#define FEATURE_DEVIATION_START_ANGLE_Z_Y			21

#define FEATURE_DEVIATION_END_ANGLE_X_Y			22
#define FEATURE_DEVIATION_END_ANGLE_X_Z			23
#define FEATURE_DEVIATION_END_ANGLE_Z_Y			24

#define FEATURE_DEVIATION_RELATIVE_CG_X			25
#define FEATURE_DEVIATION_RELATIVE_CG_Y			26
#define FEATURE_DEVIATION_RELATIVE_CG_Z			27

#define	FEATURE_DEVIATION_ORIENTATION_STRAIGHTNESS				28

#define FEATURE_DEVIATION_ORIENTATION_HEIGHT_WIDTH_RATIO		29
#define FEATURE_DEVIATION_ORIENTATION_HEIGHT_DEPTH_RATIO		30
#define FEATURE_DEVIATION_ORIENTATION_DEPTH_WIDTH_RATIO			31

#define FEATURE_DEVIATION_ORIENTATION_HEIGHT_WIDTH_RATIO_R45		32
#define FEATURE_DEVIATION_ORIENTATION_HEIGHT_DEPTH_RATIO_R45		33
#define FEATURE_DEVIATION_ORIENTATION_DEPTH_WIDTH_RATIO_R45			34

#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_START_AZIM			35
#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_START_ELEV			36
#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_START_ROLL			37

#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_END_AZIM				38
#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_END_ELEV				39
#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_END_ROLL				40

#define FEATURE_DEVIATION_ORIENTATION_AZIMUTHAL_MOVEMENTS			41
#define FEATURE_DEVIATION_ORIENTATION_ELEVATION_MOVEMENTS			42
#define FEATURE_DEVIATION_ORIENTATION_ROLL_MOVEMENTS				43

#define FEATURE_DEVIATION_ORIENTATION_AZIMUTHAL_MOVEMENTS_R45		44
#define FEATURE_DEVIATION_ORIENTATION_ELEVATION_MOVEMENTS_R45		45
#define FEATURE_DEVIATION_ORIENTATION_ROLL_MOVEMENTS_R45			46

#define FEATURE_DEVIATION_ORIENTATION_START_ANGLE_AZIM_ELEV			47
#define FEATURE_DEVIATION_ORIENTATION_START_ANGLE_AZIM_ROLL			48
#define FEATURE_DEVIATION_ORIENTATION_START_ANGLE_ROLL_ELEV			49

#define FEATURE_DEVIATION_ORIENTATION_END_ANGLE_AZIM_ELEV			50
#define FEATURE_DEVIATION_ORIENTATION_END_ANGLE_AZIM_ROLL			51
#define FEATURE_DEVIATION_ORIENTATION_END_ANGLE_ROLL_ELEV			52

#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_CG_AZIM				53
#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_CG_ELEV				54
#define FEATURE_DEVIATION_ORIENTATION_RELATIVE_CG_ROLL				55
//-----------------------------------------------------------------------------

//calculate section
//----------------------------------------------------------------------------
DEFINED_FEATURE_DEVIATION_TYPE FEATURE_DEVIATION_CALCULATE_ABS_DIFFERENCE (feature<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE> a,
														                   feature<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE> b)
{
 return((DEFINED_FEATURE_DEVIATION_TYPE)(fabsf(a.get()-b.get())));
}
//----------------------------------------------------------------------------
DEFINED_FEATURE_DEVIATION_TYPE FEATURE_DEVIATION_CALCULATE_MIN_MAX_RATIO  (feature<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE> a,
														                   feature<DEFINED_FEATURE_TYPE,DEFINED_PROPERTY_LIST_TYPE> b)
{
 return((DEFINED_FEATURE_DEVIATION_TYPE)(100.0-_min_(a.get(),b.get())*100.0/_max_(a.get(),b.get())));
}
//----------------------------------------------------------------------------
#endif

