#ifndef SAMPLE_POOL_INCLUDED
#define SAMPLE_POOL_INCLUDED

#include "sample.h"

#define DEFINED_COMPONENT_TYPE	float

typedef sample<DEFINED_COMPONENT_TYPE,2> SAMPLE_2D;
typedef sample<DEFINED_COMPONENT_TYPE,3> SAMPLE_3D;
typedef sample<DEFINED_COMPONENT_TYPE,6> SAMPLE_6D;

#define DEFINED_SAMPLE_TYPE		SAMPLE_2D

#endif

