#ifndef WEIGHT_LIST_POOL_INCLUDED
#define WEIGHT_LIST_POOL_INCLUDED

#include "weight_list.h"
#include "weight_pool.h"
#include "feature_list_pool.h"

typedef weight_list<DEFINED_WEIGHT_TYPE,DEFINED_FEATURE_LIST_TYPE,15> WEIGHT_LIST_2D;
typedef weight_list<DEFINED_WEIGHT_TYPE,DEFINED_FEATURE_LIST_TYPE,28> WEIGHT_LIST_3D;
typedef weight_list<DEFINED_WEIGHT_TYPE,DEFINED_FEATURE_LIST_TYPE,56> WEIGHT_LIST_6D;

#define DEFINED_WEIGHT_LIST_TYPE	WEIGHT_LIST_2D

//----------------------------------------------------------------------------
#if DEFINED_WEIGHT_LIST_TYPE==WEIGHT_LIST_2D
void build_weight_list(WEIGHT_LIST_2D &wl)
{
    weight<DEFINED_WEIGHT_TYPE,DEFINED_FEATURE_LIST_TYPE> w;

	w.define(WEIGHT_STRAIGHTNESS,WEIGHT_CALCULATE_STRAIGHTNESS,WEIGHT_INITIALIZE_STRAIGHTNESS);
	wl.set(0,w);
    
	w.define(WEIGHT_HEIGHT_WIDTH_RATIO,WEIGHT_CALCULATE_HEIGHT_WIDTH_RATIO,WEIGHT_INITIALIZE_HEIGHT_WIDTH_RATIO);
	wl.set(1,w);
    
	w.define(WEIGHT_HEIGHT_WIDTH_RATIO_R45,WEIGHT_CALCULATE_HEIGHT_WIDTH_RATIO_R45,WEIGHT_INITIALIZE_HEIGHT_WIDTH_RATIO_R45);
	wl.set(2,w);
    
    w.define(WEIGHT_RELATIVE_START_X,WEIGHT_CALCULATE_RELATIVE_START_X,WEIGHT_INITIALIZE_RELATIVE_START_X);
	wl.set(3,w);
    w.define(WEIGHT_RELATIVE_START_Y,WEIGHT_CALCULATE_RELATIVE_START_Y,WEIGHT_INITIALIZE_RELATIVE_START_Y);
	wl.set(4,w);
    
	w.define(WEIGHT_RELATIVE_END_X,WEIGHT_CALCULATE_RELATIVE_END_X,WEIGHT_INITIALIZE_RELATIVE_END_X);
	wl.set(5,w);
    w.define(WEIGHT_RELATIVE_END_Y,WEIGHT_CALCULATE_RELATIVE_END_Y,WEIGHT_INITIALIZE_RELATIVE_END_Y);
	wl.set(6,w);
    
    w.define(WEIGHT_HORIZONTAL_MOVEMENTS,WEIGHT_CALCULATE_HORIZONTAL_MOVEMENTS,WEIGHT_INITIALIZE_HORIZONTAL_MOVEMENTS);
	wl.set(7,w);
    w.define(WEIGHT_VERTICAL_MOVEMENTS,WEIGHT_CALCULATE_VERTICAL_MOVEMENTS,WEIGHT_INITIALIZE_VERTICAL_MOVEMENTS);
	wl.set(8,w); 

    w.define(WEIGHT_HORIZONTAL_MOVEMENTS_R45,WEIGHT_CALCULATE_HORIZONTAL_MOVEMENTS_R45,WEIGHT_INITIALIZE_HORIZONTAL_MOVEMENTS_R45);
	wl.set(9,w);
    w.define(WEIGHT_VERTICAL_MOVEMENTS_R45,WEIGHT_CALCULATE_VERTICAL_MOVEMENTS_R45,WEIGHT_INITIALIZE_VERTICAL_MOVEMENTS_R45);
	wl.set(10,w);
    
    w.define(WEIGHT_START_ANGLE_X_Y,WEIGHT_CALCULATE_START_ANGLE_X_Y,WEIGHT_INITIALIZE_START_ANGLE_X_Y);
	wl.set(11,w);
    
	w.define(WEIGHT_END_ANGLE_X_Y,WEIGHT_CALCULATE_END_ANGLE_X_Y,WEIGHT_INITIALIZE_END_ANGLE_X_Y);
	wl.set(12,w);
    
    w.define(WEIGHT_RELATIVE_CG_X,WEIGHT_CALCULATE_RELATIVE_CG_X,WEIGHT_INITIALIZE_RELATIVE_CG_X);
	wl.set(13,w);
    w.define(WEIGHT_RELATIVE_CG_Y,WEIGHT_CALCULATE_RELATIVE_CG_Y,WEIGHT_INITIALIZE_RELATIVE_CG_Y);
	wl.set(14,w);  	
}
#endif
//----------------------------------------------------------------------------
#if DEFINED_WEIGHT_LIST_TYPE==WEIGHT_LIST_3D
void build_weight_list(WEIGHT_LIST_3D &wl)
{
    weight<DEFINED_WEIGHT_TYPE,DEFINED_FEATURE_LIST_TYPE> w;
	
	w.define(WEIGHT_STRAIGHTNESS,WEIGHT_CALCULATE_STRAIGHTNESS,WEIGHT_INITIALIZE_STRAIGHTNESS);
	wl.set(0,w);
    
	w.define(WEIGHT_HEIGHT_WIDTH_RATIO,WEIGHT_CALCULATE_HEIGHT_WIDTH_RATIO,WEIGHT_INITIALIZE_HEIGHT_WIDTH_RATIO);
	wl.set(1,w);
	w.define(WEIGHT_HEIGHT_DEPTH_RATIO,WEIGHT_CALCULATE_HEIGHT_DEPTH_RATIO,WEIGHT_INITIALIZE_HEIGHT_DEPTH_RATIO);
	wl.set(2,w);
    w.define(WEIGHT_DEPTH_WIDTH_RATIO,WEIGHT_CALCULATE_DEPTH_WIDTH_RATIO,WEIGHT_INITIALIZE_DEPTH_WIDTH_RATIO);
	wl.set(3,w);
    
	w.define(WEIGHT_HEIGHT_WIDTH_RATIO_R45,WEIGHT_CALCULATE_HEIGHT_WIDTH_RATIO_R45,WEIGHT_INITIALIZE_HEIGHT_WIDTH_RATIO_R45);
	wl.set(4,w);
    w.define(WEIGHT_HEIGHT_DEPTH_RATIO_R45,WEIGHT_CALCULATE_HEIGHT_DEPTH_RATIO_R45,WEIGHT_INITIALIZE_HEIGHT_DEPTH_RATIO_R45);
	wl.set(5,w);
    w.define(WEIGHT_DEPTH_WIDTH_RATIO_R45,WEIGHT_CALCULATE_DEPTH_WIDTH_RATIO_R45,WEIGHT_INITIALIZE_DEPTH_WIDTH_RATIO_R45);
	wl.set(6,w);

    w.define(WEIGHT_RELATIVE_START_X,WEIGHT_CALCULATE_RELATIVE_START_X,WEIGHT_INITIALIZE_RELATIVE_START_X);
	wl.set(7,w);
    w.define(WEIGHT_RELATIVE_START_Y,WEIGHT_CALCULATE_RELATIVE_START_Y,WEIGHT_INITIALIZE_RELATIVE_START_Y);
	wl.set(8,w);
    w.define(WEIGHT_RELATIVE_START_Z,WEIGHT_CALCULATE_RELATIVE_START_Z,WEIGHT_INITIALIZE_RELATIVE_START_Z);
	wl.set(9,w);
 
	w.define(WEIGHT_RELATIVE_END_X,WEIGHT_CALCULATE_RELATIVE_END_X,WEIGHT_INITIALIZE_RELATIVE_END_X);
	wl.set(10,w);
    w.define(WEIGHT_RELATIVE_END_Y,WEIGHT_CALCULATE_RELATIVE_END_Y,WEIGHT_INITIALIZE_RELATIVE_END_Y);
	wl.set(11,w);
    w.define(WEIGHT_RELATIVE_END_Z,WEIGHT_CALCULATE_RELATIVE_END_Z,WEIGHT_INITIALIZE_RELATIVE_END_Z);
	wl.set(12,w);

    w.define(WEIGHT_HORIZONTAL_MOVEMENTS,WEIGHT_CALCULATE_HORIZONTAL_MOVEMENTS,WEIGHT_INITIALIZE_HORIZONTAL_MOVEMENTS);
	wl.set(13,w);
    w.define(WEIGHT_VERTICAL_MOVEMENTS,WEIGHT_CALCULATE_VERTICAL_MOVEMENTS,WEIGHT_INITIALIZE_VERTICAL_MOVEMENTS);
	wl.set(14,w);
    w.define(WEIGHT_DEPTH_MOVEMENTS,WEIGHT_CALCULATE_DEPTH_MOVEMENTS,WEIGHT_INITIALIZE_DEPTH_MOVEMENTS);
	wl.set(15,w);


    w.define(WEIGHT_HORIZONTAL_MOVEMENTS_R45,WEIGHT_CALCULATE_HORIZONTAL_MOVEMENTS_R45,WEIGHT_INITIALIZE_HORIZONTAL_MOVEMENTS_R45);
	wl.set(16,w);
    w.define(WEIGHT_VERTICAL_MOVEMENTS_R45,WEIGHT_CALCULATE_VERTICAL_MOVEMENTS_R45,WEIGHT_INITIALIZE_VERTICAL_MOVEMENTS_R45);
	wl.set(17,w);
    w.define(WEIGHT_DEPTH_MOVEMENTS_R45,WEIGHT_CALCULATE_DEPTH_MOVEMENTS_R45,WEIGHT_INITIALIZE_DEPTH_MOVEMENTS_R45);
	wl.set(18,w);

    w.define(WEIGHT_START_ANGLE_X_Y,WEIGHT_CALCULATE_START_ANGLE_X_Y,WEIGHT_INITIALIZE_START_ANGLE_X_Y);
	wl.set(19,w);
    w.define(WEIGHT_START_ANGLE_X_Z,WEIGHT_CALCULATE_START_ANGLE_X_Z,WEIGHT_INITIALIZE_START_ANGLE_X_Z);
	wl.set(20,w);
    w.define(WEIGHT_START_ANGLE_Z_Y,WEIGHT_CALCULATE_START_ANGLE_Z_Y,WEIGHT_INITIALIZE_START_ANGLE_Z_Y);
	wl.set(21,w);

	w.define(WEIGHT_END_ANGLE_X_Y,WEIGHT_CALCULATE_END_ANGLE_X_Y,WEIGHT_INITIALIZE_END_ANGLE_X_Y);
	wl.set(22,w);
    w.define(WEIGHT_END_ANGLE_X_Z,WEIGHT_CALCULATE_END_ANGLE_X_Z,WEIGHT_INITIALIZE_END_ANGLE_X_Z);
	wl.set(23,w);
    w.define(WEIGHT_END_ANGLE_Z_Y,WEIGHT_CALCULATE_END_ANGLE_Z_Y,WEIGHT_INITIALIZE_END_ANGLE_Z_Y);
	wl.set(24,w);

    w.define(WEIGHT_RELATIVE_CG_X,WEIGHT_CALCULATE_RELATIVE_CG_X,WEIGHT_INITIALIZE_RELATIVE_CG_X);
	wl.set(25,w);
    w.define(WEIGHT_RELATIVE_CG_Y,WEIGHT_CALCULATE_RELATIVE_CG_Y,WEIGHT_INITIALIZE_RELATIVE_CG_Y);
	wl.set(26,w);
    w.define(WEIGHT_RELATIVE_CG_Z,WEIGHT_CALCULATE_RELATIVE_CG_Z,WEIGHT_INITIALIZE_RELATIVE_CG_Z);
	wl.set(27,w);	
}
#endif
//----------------------------------------------------------------------------
#if DEFINED_WEIGHT_LIST_TYPE==WEIGHT_LIST_6D
void build_weight_list(WEIGHT_LIST_6D &wl)
{
  weight<DEFINED_WEIGHT_TYPE,DEFINED_FEATURE_LIST_TYPE> w;
	
  w.define(WEIGHT_STRAIGHTNESS,WEIGHT_CALCULATE_STRAIGHTNESS,WEIGHT_INITIALIZE_STRAIGHTNESS);
  wl.set(0,w);
  
  w.define(WEIGHT_HEIGHT_WIDTH_RATIO,WEIGHT_CALCULATE_HEIGHT_WIDTH_RATIO,WEIGHT_INITIALIZE_HEIGHT_WIDTH_RATIO);
  wl.set(1,w);
  w.define(WEIGHT_HEIGHT_DEPTH_RATIO,WEIGHT_CALCULATE_HEIGHT_DEPTH_RATIO,WEIGHT_INITIALIZE_HEIGHT_DEPTH_RATIO);
  wl.set(2,w);
  w.define(WEIGHT_DEPTH_WIDTH_RATIO,WEIGHT_CALCULATE_DEPTH_WIDTH_RATIO,WEIGHT_INITIALIZE_DEPTH_WIDTH_RATIO);
  wl.set(3,w);
    
  w.define(WEIGHT_HEIGHT_WIDTH_RATIO_R45,WEIGHT_CALCULATE_HEIGHT_WIDTH_RATIO_R45,WEIGHT_INITIALIZE_HEIGHT_WIDTH_RATIO_R45);
  wl.set(4,w);
  w.define(WEIGHT_HEIGHT_DEPTH_RATIO_R45,WEIGHT_CALCULATE_HEIGHT_DEPTH_RATIO_R45,WEIGHT_INITIALIZE_HEIGHT_DEPTH_RATIO_R45);
  wl.set(5,w);
  w.define(WEIGHT_DEPTH_WIDTH_RATIO_R45,WEIGHT_CALCULATE_DEPTH_WIDTH_RATIO_R45,WEIGHT_INITIALIZE_DEPTH_WIDTH_RATIO_R45);
  wl.set(6,w);

  w.define(WEIGHT_RELATIVE_START_X,WEIGHT_CALCULATE_RELATIVE_START_X,WEIGHT_INITIALIZE_RELATIVE_START_X);
  wl.set(7,w);
  w.define(WEIGHT_RELATIVE_START_Y,WEIGHT_CALCULATE_RELATIVE_START_Y,WEIGHT_INITIALIZE_RELATIVE_START_Y);
  wl.set(8,w);
  w.define(WEIGHT_RELATIVE_START_Z,WEIGHT_CALCULATE_RELATIVE_START_Z,WEIGHT_INITIALIZE_RELATIVE_START_Z);
  wl.set(9,w);
 
  w.define(WEIGHT_RELATIVE_END_X,WEIGHT_CALCULATE_RELATIVE_END_X,WEIGHT_INITIALIZE_RELATIVE_END_X);
  wl.set(10,w);
  w.define(WEIGHT_RELATIVE_END_Y,WEIGHT_CALCULATE_RELATIVE_END_Y,WEIGHT_INITIALIZE_RELATIVE_END_Y);
  wl.set(11,w);
  w.define(WEIGHT_RELATIVE_END_Z,WEIGHT_CALCULATE_RELATIVE_END_Z,WEIGHT_INITIALIZE_RELATIVE_END_Z);
  wl.set(12,w);

  w.define(WEIGHT_HORIZONTAL_MOVEMENTS,WEIGHT_CALCULATE_HORIZONTAL_MOVEMENTS,WEIGHT_INITIALIZE_HORIZONTAL_MOVEMENTS);
  wl.set(13,w);
  w.define(WEIGHT_VERTICAL_MOVEMENTS,WEIGHT_CALCULATE_VERTICAL_MOVEMENTS,WEIGHT_INITIALIZE_VERTICAL_MOVEMENTS);
  wl.set(14,w);
  w.define(WEIGHT_DEPTH_MOVEMENTS,WEIGHT_CALCULATE_DEPTH_MOVEMENTS,WEIGHT_INITIALIZE_DEPTH_MOVEMENTS);
  wl.set(15,w);


  w.define(WEIGHT_HORIZONTAL_MOVEMENTS_R45,WEIGHT_CALCULATE_HORIZONTAL_MOVEMENTS_R45,WEIGHT_INITIALIZE_HORIZONTAL_MOVEMENTS_R45);
  wl.set(16,w);
  w.define(WEIGHT_VERTICAL_MOVEMENTS_R45,WEIGHT_CALCULATE_VERTICAL_MOVEMENTS_R45,WEIGHT_INITIALIZE_VERTICAL_MOVEMENTS_R45);
  wl.set(17,w);
  w.define(WEIGHT_DEPTH_MOVEMENTS_R45,WEIGHT_CALCULATE_DEPTH_MOVEMENTS_R45,WEIGHT_INITIALIZE_DEPTH_MOVEMENTS_R45);
  wl.set(18,w);

  w.define(WEIGHT_START_ANGLE_X_Y,WEIGHT_CALCULATE_START_ANGLE_X_Y,WEIGHT_INITIALIZE_START_ANGLE_X_Y);
  wl.set(19,w);
  w.define(WEIGHT_START_ANGLE_X_Z,WEIGHT_CALCULATE_START_ANGLE_X_Z,WEIGHT_INITIALIZE_START_ANGLE_X_Z);
  wl.set(20,w);
  w.define(WEIGHT_START_ANGLE_Z_Y,WEIGHT_CALCULATE_START_ANGLE_Z_Y,WEIGHT_INITIALIZE_START_ANGLE_Z_Y);
  wl.set(21,w);

  w.define(WEIGHT_END_ANGLE_X_Y,WEIGHT_CALCULATE_END_ANGLE_X_Y,WEIGHT_INITIALIZE_END_ANGLE_X_Y);
  wl.set(22,w);
  w.define(WEIGHT_END_ANGLE_X_Z,WEIGHT_CALCULATE_END_ANGLE_X_Z,WEIGHT_INITIALIZE_END_ANGLE_X_Z);
  wl.set(23,w);
  w.define(WEIGHT_END_ANGLE_Z_Y,WEIGHT_CALCULATE_END_ANGLE_Z_Y,WEIGHT_INITIALIZE_END_ANGLE_Z_Y);
  wl.set(24,w);

  w.define(WEIGHT_RELATIVE_CG_X,WEIGHT_CALCULATE_RELATIVE_CG_X,WEIGHT_INITIALIZE_RELATIVE_CG_X);
  wl.set(25,w);
  w.define(WEIGHT_RELATIVE_CG_Y,WEIGHT_CALCULATE_RELATIVE_CG_Y,WEIGHT_INITIALIZE_RELATIVE_CG_Y);
  wl.set(26,w);
  w.define(WEIGHT_RELATIVE_CG_Z,WEIGHT_CALCULATE_RELATIVE_CG_Z,WEIGHT_INITIALIZE_RELATIVE_CG_Z);
  wl.set(27,w);


  w.define(WEIGHT_ORIENTATION_STRAIGHTNESS,WEIGHT_CALCULATE_ORIENTATION_STRAIGHTNESS,WEIGHT_INITIALIZE_ORIENTATION_STRAIGHTNESS);
  wl.set(28,w);
    
  w.define(WEIGHT_ORIENTATION_HEIGHT_WIDTH_RATIO,WEIGHT_CALCULATE_ORIENTATION_HEIGHT_WIDTH_RATIO,WEIGHT_INITIALIZE_ORIENTATION_HEIGHT_WIDTH_RATIO);
  wl.set(29,w);
  w.define(WEIGHT_ORIENTATION_HEIGHT_DEPTH_RATIO,WEIGHT_CALCULATE_ORIENTATION_HEIGHT_DEPTH_RATIO,WEIGHT_INITIALIZE_ORIENTATION_HEIGHT_DEPTH_RATIO);
  wl.set(30,w);
  w.define(WEIGHT_ORIENTATION_DEPTH_WIDTH_RATIO,WEIGHT_CALCULATE_ORIENTATION_DEPTH_WIDTH_RATIO,WEIGHT_INITIALIZE_ORIENTATION_DEPTH_WIDTH_RATIO);
  wl.set(31,w);
    
  w.define(WEIGHT_ORIENTATION_HEIGHT_WIDTH_RATIO_R45,WEIGHT_CALCULATE_ORIENTATION_HEIGHT_WIDTH_RATIO_R45,WEIGHT_INITIALIZE_ORIENTATION_HEIGHT_WIDTH_RATIO_R45);
  wl.set(32,w);
  w.define(WEIGHT_ORIENTATION_HEIGHT_DEPTH_RATIO_R45,WEIGHT_CALCULATE_ORIENTATION_HEIGHT_DEPTH_RATIO_R45,WEIGHT_INITIALIZE_ORIENTATION_HEIGHT_DEPTH_RATIO_R45);
  wl.set(33,w);
  w.define(WEIGHT_ORIENTATION_DEPTH_WIDTH_RATIO_R45,WEIGHT_CALCULATE_ORIENTATION_DEPTH_WIDTH_RATIO_R45,WEIGHT_INITIALIZE_ORIENTATION_DEPTH_WIDTH_RATIO_R45);
  wl.set(34,w);

  w.define(WEIGHT_ORIENTATION_RELATIVE_START_AZIM,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_START_AZIM,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_START_AZIM);
  wl.set(35,w);
  w.define(WEIGHT_ORIENTATION_RELATIVE_START_ELEV,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_START_ELEV,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_START_ELEV);
  wl.set(36,w);
  w.define(WEIGHT_ORIENTATION_RELATIVE_START_ROLL,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_START_ROLL,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_START_ROLL);
  wl.set(37,w);
 
  w.define(WEIGHT_ORIENTATION_RELATIVE_END_AZIM,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_END_AZIM,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_END_AZIM);
  wl.set(38,w);
  w.define(WEIGHT_ORIENTATION_RELATIVE_END_ELEV,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_END_ELEV,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_END_ELEV);
  wl.set(39,w);
  w.define(WEIGHT_ORIENTATION_RELATIVE_END_ROLL,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_END_ROLL,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_END_ROLL);
  wl.set(40,w);

  w.define(WEIGHT_ORIENTATION_AZIMUTHAL_MOVEMENTS,WEIGHT_CALCULATE_ORIENTATION_AZIMUTHAL_MOVEMENTS,WEIGHT_INITIALIZE_ORIENTATION_AZIMUTHAL_MOVEMENTS);
  wl.set(41,w);
  w.define(WEIGHT_ORIENTATION_ELEVATION_MOVEMENTS,WEIGHT_CALCULATE_ORIENTATION_ELEVATION_MOVEMENTS,WEIGHT_INITIALIZE_ORIENTATION_ELEVATION_MOVEMENTS);
  wl.set(42,w);
  w.define(WEIGHT_ORIENTATION_ROLL_MOVEMENTS,WEIGHT_CALCULATE_ORIENTATION_ROLL_MOVEMENTS,WEIGHT_INITIALIZE_ORIENTATION_ROLL_MOVEMENTS);
  wl.set(43,w);


  w.define(WEIGHT_ORIENTATION_AZIMUTHAL_MOVEMENTS_R45,WEIGHT_CALCULATE_ORIENTATION_AZIMUTHAL_MOVEMENTS_R45,WEIGHT_INITIALIZE_ORIENTATION_AZIMUTHAL_MOVEMENTS_R45);
  wl.set(44,w);
  w.define(WEIGHT_ORIENTATION_ELEVATION_MOVEMENTS_R45,WEIGHT_CALCULATE_ORIENTATION_ELEVATION_MOVEMENTS_R45,WEIGHT_INITIALIZE_ORIENTATION_ELEVATION_MOVEMENTS_R45);
  wl.set(45,w);
  w.define(WEIGHT_ORIENTATION_ROLL_MOVEMENTS_R45,WEIGHT_CALCULATE_ORIENTATION_ROLL_MOVEMENTS_R45,WEIGHT_INITIALIZE_ORIENTATION_ROLL_MOVEMENTS_R45);
  wl.set(46,w);

  w.define(WEIGHT_ORIENTATION_START_ANGLE_AZIM_ELEV,WEIGHT_CALCULATE_ORIENTATION_START_ANGLE_AZIM_ELEV,WEIGHT_INITIALIZE_ORIENTATION_START_ANGLE_AZIM_ELEV);
  wl.set(47,w);
  w.define(WEIGHT_ORIENTATION_START_ANGLE_AZIM_ROLL,WEIGHT_CALCULATE_ORIENTATION_START_ANGLE_AZIM_ROLL,WEIGHT_INITIALIZE_ORIENTATION_START_ANGLE_AZIM_ROLL);
  wl.set(48,w);
  w.define(WEIGHT_ORIENTATION_START_ANGLE_ROLL_ELEV,WEIGHT_CALCULATE_ORIENTATION_START_ANGLE_ROLL_ELEV,WEIGHT_INITIALIZE_ORIENTATION_START_ANGLE_ROLL_ELEV);
  wl.set(49,w);

  w.define(WEIGHT_ORIENTATION_END_ANGLE_AZIM_ELEV,WEIGHT_CALCULATE_ORIENTATION_END_ANGLE_AZIM_ELEV,WEIGHT_INITIALIZE_ORIENTATION_END_ANGLE_AZIM_ELEV);
  wl.set(50,w);
  w.define(WEIGHT_ORIENTATION_END_ANGLE_AZIM_ROLL,WEIGHT_CALCULATE_ORIENTATION_END_ANGLE_AZIM_ROLL,WEIGHT_INITIALIZE_ORIENTATION_END_ANGLE_AZIM_ROLL);
  wl.set(51,w);
  w.define(WEIGHT_ORIENTATION_END_ANGLE_ROLL_ELEV,WEIGHT_CALCULATE_ORIENTATION_END_ANGLE_ROLL_ELEV,WEIGHT_INITIALIZE_ORIENTATION_END_ANGLE_ROLL_ELEV);
  wl.set(52,w);

  w.define(WEIGHT_ORIENTATION_RELATIVE_CG_AZIM,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_CG_AZIM,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_CG_AZIM);
  wl.set(53,w);
  w.define(WEIGHT_ORIENTATION_RELATIVE_CG_ELEV,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_CG_ELEV,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_CG_ELEV);
  wl.set(54,w);
  w.define(WEIGHT_ORIENTATION_RELATIVE_CG_ROLL,WEIGHT_CALCULATE_ORIENTATION_RELATIVE_CG_ROLL,WEIGHT_INITIALIZE_ORIENTATION_RELATIVE_CG_ROLL);
  wl.set(55,w);
}
#endif
//----------------------------------------------------------------------------


#endif
