#! /bin/sh
##
# regenerate all files which are constructed by the autoconf, automake and
# libtool tool-chain.
#
# Author: Tamer Fahmy <tamer@tammura.at>
#

# set -x -v

aclocal -I cfg/m4 \
&& libtoolize --force --copy \
&& autoheader \
&& automake --add-missing --copy \
&& autoconf
