# This python script allows the user to automate the configuration of the build
DEBUG=1
ENABLE_CORBA=1
ENABLE_LIVE=1
ENABLE_OMNIEVENTS=0
ENABLE_SHARED=0
ENABLE_OMNIORBPY=1
ENABLE_PHANTOM_MIDDLEWARE=0
ENABLE_JAVA=0
ENABLE_MOBILAB=0
