/* kokyu_config.h,v 1.2 2004/01/28 01:35:44 storri Exp */
#ifndef KOKYU_CONFIG_H
#define KOKYU_CONFIG_H

#define CONFIG_DSTREAM_DSRT_DISPATCH
#define CONFIG_DSTREAM_DSRT_CV_DISPATCH
#define CONFIG_DSTREAM_DSRT_DIRECT_DISPATCH
#define CONFIG_DSTREAM_DSRT_DISPATCH_IMPL

#endif /* KOKYU_CONFIG_H */
