.\" Process this file with
.\" groff -man -Tascii sowin-config.1
.\"
.TH sowin-config 1 "AUGUST 2001" "Library Configuration" "User Manuals"
.SH NAME
sowin-config \- Display SoWin Library Configuration
.SH SYNOPSIS
.B sowin-config 
.I OPTION 
.B [
.I OPTION
.B ... ]
.SH DESCRIPTION
.B sowin-config
is a script that is used to display what compiler flags and libraries were
used when SoWin was built.
.SH OPTIONS
.IP --version
Return SoWin version string
.IP --help
Display sowin-config usage information
.IP --cppflags
Return C pre-processor flags for use when compiling with SoWin
.IP --cxxflags
Return C++ compiler flags for use when compiling with SoWin
.IP --ldflags
Return linker flags needed when linking against SoWin
.IP --libs
Return libraries one must link with when using SoWin
.IP --alternate=<config-name>
Set SoWin configuration to something other than default (when using
multiple SoWin configurations).
.SH AUTHORS
Steve Robbins <smr@debian.org>, and
.br
Lars J. Aas <larsa@coin3d.org>
.
