// OT_CORBA.idl
#ifndef _OT_CORBA_IDL
#define _OT_CORBA_IDL

#ifdef USE_LIVE
#include "OTGraph.idl"
#endif

module OT_CORBA {
  struct EventAttribute {
    string name;
    any value;
  };

  typedef sequence<EventAttribute> Event;
  typedef sequence<float> FloatVector;

#ifdef USE_LIVE
  interface OTNode: OTGraph::Node {
#else
  interface OTNode {
#endif
  };

  interface TransformNode : OTNode {
    Event transformEvent(in Event ev);
  };

  interface OTEntity {
    oneway void setEvent(in Event ev);    
  };

  interface OTSink : OTNode {
    void setEntity(in OTEntity entity);
    OTEntity getEntity();
  };

  interface OTSource : OTEntity, OTNode { };

};

#endif //_OT_CORBA_IDL