// OT_CORBA.idl
module OT_CORBA {
  const string OT_CORBA__doc__ = "This is the CORBA Module for OpenTracker";

  struct EventAttribute {
    string name;
    any value;
  };

  typedef sequence<EventAttribute> Event;

  interface Node {
    void setEvent(in Event ev);
  };

  const string Node__doc__ = "The Node is the superclass of all the CORBA objects that are either OpenTracker nodes or are invoked by OpenTracker ndoes.";

  interface TransformNode : Node {
    Event transformEvent(in Event ev);
  };

  interface OTNode : Node {
  };
  const string OTNode__doc__ = "The OTNode is the superclass of all the OpenTracker nodes that are also CORBA objects.";

  interface OTSource : OTNode { 
    void push();
  };

  interface OTSink : OTNode { }; // currently unused

  interface Source : Node { }; // currently unused

  interface Sink : Node { };
};
