/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	

/* DO NOT EDIT - THIS FILE AUTOMATICALLY GENERATED BY server_dispatch.py SCRIPT */
#include "cr_spu.h"
#include "chromium.h"
#include "cr_error.h"
#include "server_dispatch.h"
#include "server.h"
#include "cr_unpack.h"

CRCurrentStatePointers crServerCurrent;

void SERVER_DISPATCH_APIENTRY crServerDispatchActiveTextureARB( GLenum texture )
{
	crStateActiveTextureARB( texture );
	cr_server.head_spu->dispatch_table.ActiveTextureARB( texture );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchAlphaFunc( GLenum func, GLclampf ref )
{
	crStateAlphaFunc( func, ref );
	cr_server.head_spu->dispatch_table.AlphaFunc( func, ref );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchBegin( GLenum mode )
{
	crStateBegin( mode );
	cr_server.head_spu->dispatch_table.Begin( mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchBindTexture( GLenum target, GLuint texture )
{
	crStateBindTexture( target, texture );
	cr_server.head_spu->dispatch_table.BindTexture( target, texture );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchBitmap( GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap )
{
	crStateBitmap( width, height, xorig, yorig, xmove, ymove, bitmap );
	cr_server.head_spu->dispatch_table.Bitmap( width, height, xorig, yorig, xmove, ymove, bitmap );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchBlendColorEXT( GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha )
{
	crStateBlendColorEXT( red, green, blue, alpha );
	cr_server.head_spu->dispatch_table.BlendColorEXT( red, green, blue, alpha );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchBlendFunc( GLenum sfactor, GLenum dfactor )
{
	crStateBlendFunc( sfactor, dfactor );
	cr_server.head_spu->dispatch_table.BlendFunc( sfactor, dfactor );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchClearAccum( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha )
{
	crStateClearAccum( red, green, blue, alpha );
	cr_server.head_spu->dispatch_table.ClearAccum( red, green, blue, alpha );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchClearColor( GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha )
{
	crStateClearColor( red, green, blue, alpha );
	cr_server.head_spu->dispatch_table.ClearColor( red, green, blue, alpha );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchClearDepth( GLclampd depth )
{
	crStateClearDepth( depth );
	cr_server.head_spu->dispatch_table.ClearDepth( depth );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchClearIndex( GLfloat c )
{
	crStateClearIndex( c );
	cr_server.head_spu->dispatch_table.ClearIndex( c );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchClearStencil( GLint s )
{
	crStateClearStencil( s );
	cr_server.head_spu->dispatch_table.ClearStencil( s );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchClientActiveTextureARB( GLenum texture )
{
	crStateClientActiveTextureARB( texture );
	cr_server.head_spu->dispatch_table.ClientActiveTextureARB( texture );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchClipPlane( GLenum plane, const GLdouble *equation )
{
	crStateClipPlane( plane, equation );
	cr_server.head_spu->dispatch_table.ClipPlane( plane, equation );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchColor3fv( const GLfloat *v )
{
	crStateColor3fv( v );
	cr_server.head_spu->dispatch_table.Color3fv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchColor4fv( const GLfloat *v )
{
	crStateColor4fv( v );
	cr_server.head_spu->dispatch_table.Color4fv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchColorMask( GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha )
{
	crStateColorMask( red, green, blue, alpha );
	cr_server.head_spu->dispatch_table.ColorMask( red, green, blue, alpha );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchColorMaterial( GLenum face, GLenum mode )
{
	crStateColorMaterial( face, mode );
	cr_server.head_spu->dispatch_table.ColorMaterial( face, mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchColorPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer )
{
	crStateColorPointer( size, type, stride, pointer );
	cr_server.head_spu->dispatch_table.ColorPointer( size, type, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchCombinerInputNV( GLenum stage, GLenum portion, GLenum variable, GLenum input, GLenum mapping, GLenum componentUsage )
{
	crStateCombinerInputNV( stage, portion, variable, input, mapping, componentUsage );
	cr_server.head_spu->dispatch_table.CombinerInputNV( stage, portion, variable, input, mapping, componentUsage );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchCombinerOutputNV( GLenum stage, GLenum portion, GLenum abOutput, GLenum cdOutput, GLenum sumOutput, GLenum scale, GLenum bias, GLboolean abDotProduct, GLboolean cdDotProduct, GLboolean muxSum )
{
	crStateCombinerOutputNV( stage, portion, abOutput, cdOutput, sumOutput, scale, bias, abDotProduct, cdDotProduct, muxSum );
	cr_server.head_spu->dispatch_table.CombinerOutputNV( stage, portion, abOutput, cdOutput, sumOutput, scale, bias, abDotProduct, cdDotProduct, muxSum );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchCombinerParameterfNV( GLenum pname, GLfloat param )
{
	crStateCombinerParameterfNV( pname, param );
	cr_server.head_spu->dispatch_table.CombinerParameterfNV( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchCombinerParameterfvNV( GLenum pname, const GLfloat *params )
{
	crStateCombinerParameterfvNV( pname, params );
	cr_server.head_spu->dispatch_table.CombinerParameterfvNV( pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchCombinerParameteriNV( GLenum pname, GLint param )
{
	crStateCombinerParameteriNV( pname, param );
	cr_server.head_spu->dispatch_table.CombinerParameteriNV( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchCombinerParameterivNV( GLenum pname, const GLint *params )
{
	crStateCombinerParameterivNV( pname, params );
	cr_server.head_spu->dispatch_table.CombinerParameterivNV( pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchCombinerStageParameterfvNV( GLenum stage, GLenum pname, const GLfloat *params )
{
	crStateCombinerStageParameterfvNV( stage, pname, params );
	cr_server.head_spu->dispatch_table.CombinerStageParameterfvNV( stage, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchCullFace( GLenum mode )
{
	crStateCullFace( mode );
	cr_server.head_spu->dispatch_table.CullFace( mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchDeleteLists( GLuint list, GLsizei range )
{
	crStateDeleteLists( list, range );
	cr_server.head_spu->dispatch_table.DeleteLists( list, range );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchDeleteTextures( GLsizei n, const GLuint *textures )
{
	crStateDeleteTextures( n, textures );
	cr_server.head_spu->dispatch_table.DeleteTextures( n, textures );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchDepthFunc( GLenum func )
{
	crStateDepthFunc( func );
	cr_server.head_spu->dispatch_table.DepthFunc( func );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchDepthMask( GLboolean flag )
{
	crStateDepthMask( flag );
	cr_server.head_spu->dispatch_table.DepthMask( flag );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchDepthRange( GLclampd zNear, GLclampd zFar )
{
	crStateDepthRange( zNear, zFar );
	cr_server.head_spu->dispatch_table.DepthRange( zNear, zFar );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchDisable( GLenum cap )
{
	crStateDisable( cap );
	cr_server.head_spu->dispatch_table.Disable( cap );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchDisableClientState( GLenum array )
{
	crStateDisableClientState( array );
	cr_server.head_spu->dispatch_table.DisableClientState( array );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchDrawBuffer( GLenum mode )
{
	crStateDrawBuffer( mode );
	cr_server.head_spu->dispatch_table.DrawBuffer( mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchEdgeFlagPointer( GLsizei stride, const GLvoid *pointer )
{
	crStateEdgeFlagPointer( stride, pointer );
	cr_server.head_spu->dispatch_table.EdgeFlagPointer( stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchEnable( GLenum cap )
{
	crStateEnable( cap );
	cr_server.head_spu->dispatch_table.Enable( cap );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchEnableClientState( GLenum array )
{
	crStateEnableClientState( array );
	cr_server.head_spu->dispatch_table.EnableClientState( array );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchEnd( void )
{
	crStateEnd(  );
	cr_server.head_spu->dispatch_table.End(  );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchEndList( void )
{
	crStateEndList(  );
	cr_server.head_spu->dispatch_table.EndList(  );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFeedbackBuffer( GLsizei size, GLenum type, GLfloat *buffer )
{
	crStateFeedbackBuffer( size, type, buffer );
	cr_server.head_spu->dispatch_table.FeedbackBuffer( size, type, buffer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFinalCombinerInputNV( GLenum variable, GLenum input, GLenum mapping, GLenum componentUsage )
{
	crStateFinalCombinerInputNV( variable, input, mapping, componentUsage );
	cr_server.head_spu->dispatch_table.FinalCombinerInputNV( variable, input, mapping, componentUsage );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFogCoordPointerEXT( GLenum type, GLsizei stride, const GLvoid *pointer )
{
	crStateFogCoordPointerEXT( type, stride, pointer );
	cr_server.head_spu->dispatch_table.FogCoordPointerEXT( type, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFogf( GLenum pname, GLfloat param )
{
	crStateFogf( pname, param );
	cr_server.head_spu->dispatch_table.Fogf( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFogfv( GLenum pname, const GLfloat *params )
{
	crStateFogfv( pname, params );
	cr_server.head_spu->dispatch_table.Fogfv( pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFogi( GLenum pname, GLint param )
{
	crStateFogi( pname, param );
	cr_server.head_spu->dispatch_table.Fogi( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFogiv( GLenum pname, const GLint *params )
{
	crStateFogiv( pname, params );
	cr_server.head_spu->dispatch_table.Fogiv( pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFrontFace( GLenum mode )
{
	crStateFrontFace( mode );
	cr_server.head_spu->dispatch_table.FrontFace( mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchFrustum( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar )
{
	crStateFrustum( left, right, bottom, top, zNear, zFar );
	cr_server.head_spu->dispatch_table.Frustum( left, right, bottom, top, zNear, zFar );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchHint( GLenum target, GLenum mode )
{
	crStateHint( target, mode );
	cr_server.head_spu->dispatch_table.Hint( target, mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchIndexMask( GLuint mask )
{
	crStateIndexMask( mask );
	cr_server.head_spu->dispatch_table.IndexMask( mask );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchIndexPointer( GLenum type, GLsizei stride, const GLvoid *pointer )
{
	crStateIndexPointer( type, stride, pointer );
	cr_server.head_spu->dispatch_table.IndexPointer( type, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchInitNames( void )
{
	crStateInitNames(  );
	cr_server.head_spu->dispatch_table.InitNames(  );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchInterleavedArrays( GLenum format, GLsizei stride, const GLvoid *pointer )
{
	crStateInterleavedArrays( format, stride, pointer );
	cr_server.head_spu->dispatch_table.InterleavedArrays( format, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLightModelf( GLenum pname, GLfloat param )
{
	crStateLightModelf( pname, param );
	cr_server.head_spu->dispatch_table.LightModelf( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLightModelfv( GLenum pname, const GLfloat *params )
{
	crStateLightModelfv( pname, params );
	cr_server.head_spu->dispatch_table.LightModelfv( pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLightModeli( GLenum pname, GLint param )
{
	crStateLightModeli( pname, param );
	cr_server.head_spu->dispatch_table.LightModeli( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLightModeliv( GLenum pname, const GLint *params )
{
	crStateLightModeliv( pname, params );
	cr_server.head_spu->dispatch_table.LightModeliv( pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLightf( GLenum light, GLenum pname, GLfloat param )
{
	crStateLightf( light, pname, param );
	cr_server.head_spu->dispatch_table.Lightf( light, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLightfv( GLenum light, GLenum pname, const GLfloat *params )
{
	crStateLightfv( light, pname, params );
	cr_server.head_spu->dispatch_table.Lightfv( light, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLighti( GLenum light, GLenum pname, GLint param )
{
	crStateLighti( light, pname, param );
	cr_server.head_spu->dispatch_table.Lighti( light, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLightiv( GLenum light, GLenum pname, const GLint *params )
{
	crStateLightiv( light, pname, params );
	cr_server.head_spu->dispatch_table.Lightiv( light, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLineStipple( GLint factor, GLushort pattern )
{
	crStateLineStipple( factor, pattern );
	cr_server.head_spu->dispatch_table.LineStipple( factor, pattern );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLineWidth( GLfloat width )
{
	crStateLineWidth( width );
	cr_server.head_spu->dispatch_table.LineWidth( width );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchListBase( GLuint base )
{
	crStateListBase( base );
	cr_server.head_spu->dispatch_table.ListBase( base );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLoadName( GLuint name )
{
	crStateLoadName( name );
	cr_server.head_spu->dispatch_table.LoadName( name );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLoadTransposeMatrixdARB( const GLdouble *m )
{
	crStateLoadTransposeMatrixdARB( m );
	cr_server.head_spu->dispatch_table.LoadTransposeMatrixdARB( m );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLoadTransposeMatrixfARB( const GLfloat *m )
{
	crStateLoadTransposeMatrixfARB( m );
	cr_server.head_spu->dispatch_table.LoadTransposeMatrixfARB( m );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchLogicOp( GLenum opcode )
{
	crStateLogicOp( opcode );
	cr_server.head_spu->dispatch_table.LogicOp( opcode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMap1d( GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points )
{
	crStateMap1d( target, u1, u2, stride, order, points );
	cr_server.head_spu->dispatch_table.Map1d( target, u1, u2, stride, order, points );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMap1f( GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points )
{
	crStateMap1f( target, u1, u2, stride, order, points );
	cr_server.head_spu->dispatch_table.Map1f( target, u1, u2, stride, order, points );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMap2d( GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points )
{
	crStateMap2d( target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points );
	cr_server.head_spu->dispatch_table.Map2d( target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMap2f( GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points )
{
	crStateMap2f( target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points );
	cr_server.head_spu->dispatch_table.Map2f( target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMapGrid1d( GLint un, GLdouble u1, GLdouble u2 )
{
	crStateMapGrid1d( un, u1, u2 );
	cr_server.head_spu->dispatch_table.MapGrid1d( un, u1, u2 );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMapGrid1f( GLint un, GLfloat u1, GLfloat u2 )
{
	crStateMapGrid1f( un, u1, u2 );
	cr_server.head_spu->dispatch_table.MapGrid1f( un, u1, u2 );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMapGrid2d( GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2 )
{
	crStateMapGrid2d( un, u1, u2, vn, v1, v2 );
	cr_server.head_spu->dispatch_table.MapGrid2d( un, u1, u2, vn, v1, v2 );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMapGrid2f( GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2 )
{
	crStateMapGrid2f( un, u1, u2, vn, v1, v2 );
	cr_server.head_spu->dispatch_table.MapGrid2f( un, u1, u2, vn, v1, v2 );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMaterialf( GLenum face, GLenum pname, GLfloat param )
{
	crStateMaterialf( face, pname, param );
	cr_server.head_spu->dispatch_table.Materialf( face, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMaterialfv( GLenum face, GLenum pname, const GLfloat *params )
{
	crStateMaterialfv( face, pname, params );
	cr_server.head_spu->dispatch_table.Materialfv( face, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMateriali( GLenum face, GLenum pname, GLint param )
{
	crStateMateriali( face, pname, param );
	cr_server.head_spu->dispatch_table.Materiali( face, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMaterialiv( GLenum face, GLenum pname, const GLint *params )
{
	crStateMaterialiv( face, pname, params );
	cr_server.head_spu->dispatch_table.Materialiv( face, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMatrixMode( GLenum mode )
{
	crStateMatrixMode( mode );
	cr_server.head_spu->dispatch_table.MatrixMode( mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMultMatrixd( const GLdouble *m )
{
	crStateMultMatrixd( m );
	cr_server.head_spu->dispatch_table.MultMatrixd( m );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMultMatrixf( const GLfloat *m )
{
	crStateMultMatrixf( m );
	cr_server.head_spu->dispatch_table.MultMatrixf( m );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMultTransposeMatrixdARB( const GLdouble *m )
{
	crStateMultTransposeMatrixdARB( m );
	cr_server.head_spu->dispatch_table.MultTransposeMatrixdARB( m );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchMultTransposeMatrixfARB( const GLfloat *m )
{
	crStateMultTransposeMatrixfARB( m );
	cr_server.head_spu->dispatch_table.MultTransposeMatrixfARB( m );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchNewList( GLuint list, GLenum mode )
{
	crStateNewList( list, mode );
	cr_server.head_spu->dispatch_table.NewList( list, mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchNormalPointer( GLenum type, GLsizei stride, const GLvoid *pointer )
{
	crStateNormalPointer( type, stride, pointer );
	cr_server.head_spu->dispatch_table.NormalPointer( type, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchOrtho( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar )
{
	crStateOrtho( left, right, bottom, top, zNear, zFar );
	cr_server.head_spu->dispatch_table.Ortho( left, right, bottom, top, zNear, zFar );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPassThrough( GLfloat token )
{
	crStatePassThrough( token );
	cr_server.head_spu->dispatch_table.PassThrough( token );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPixelMapfv( GLenum map, GLsizei mapsize, const GLfloat *values )
{
	crStatePixelMapfv( map, mapsize, values );
	cr_server.head_spu->dispatch_table.PixelMapfv( map, mapsize, values );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPixelMapuiv( GLenum map, GLsizei mapsize, const GLuint *values )
{
	crStatePixelMapuiv( map, mapsize, values );
	cr_server.head_spu->dispatch_table.PixelMapuiv( map, mapsize, values );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPixelMapusv( GLenum map, GLsizei mapsize, const GLushort *values )
{
	crStatePixelMapusv( map, mapsize, values );
	cr_server.head_spu->dispatch_table.PixelMapusv( map, mapsize, values );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPixelStoref( GLenum pname, GLfloat param )
{
	crStatePixelStoref( pname, param );
	cr_server.head_spu->dispatch_table.PixelStoref( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPixelStorei( GLenum pname, GLint param )
{
	crStatePixelStorei( pname, param );
	cr_server.head_spu->dispatch_table.PixelStorei( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPixelTransferf( GLenum pname, GLfloat param )
{
	crStatePixelTransferf( pname, param );
	cr_server.head_spu->dispatch_table.PixelTransferf( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPixelTransferi( GLenum pname, GLint param )
{
	crStatePixelTransferi( pname, param );
	cr_server.head_spu->dispatch_table.PixelTransferi( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPixelZoom( GLfloat xfactor, GLfloat yfactor )
{
	crStatePixelZoom( xfactor, yfactor );
	cr_server.head_spu->dispatch_table.PixelZoom( xfactor, yfactor );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPointParameterfARB( GLenum pname, GLfloat param )
{
	crStatePointParameterfARB( pname, param );
	cr_server.head_spu->dispatch_table.PointParameterfARB( pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPointParameterfvARB( GLenum pname, const GLfloat *params )
{
	crStatePointParameterfvARB( pname, params );
	cr_server.head_spu->dispatch_table.PointParameterfvARB( pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPointSize( GLfloat size )
{
	crStatePointSize( size );
	cr_server.head_spu->dispatch_table.PointSize( size );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPolygonMode( GLenum face, GLenum mode )
{
	crStatePolygonMode( face, mode );
	cr_server.head_spu->dispatch_table.PolygonMode( face, mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPolygonOffset( GLfloat factor, GLfloat units )
{
	crStatePolygonOffset( factor, units );
	cr_server.head_spu->dispatch_table.PolygonOffset( factor, units );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPolygonStipple( const GLubyte *mask )
{
	crStatePolygonStipple( mask );
	cr_server.head_spu->dispatch_table.PolygonStipple( mask );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPopAttrib( void )
{
	crStatePopAttrib(  );
	cr_server.head_spu->dispatch_table.PopAttrib(  );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPopMatrix( void )
{
	crStatePopMatrix(  );
	cr_server.head_spu->dispatch_table.PopMatrix(  );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPopName( void )
{
	crStatePopName(  );
	cr_server.head_spu->dispatch_table.PopName(  );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPrioritizeTextures( GLsizei n, const GLuint *textures, const GLclampf *priorities )
{
	crStatePrioritizeTextures( n, textures, priorities );
	cr_server.head_spu->dispatch_table.PrioritizeTextures( n, textures, priorities );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPushAttrib( GLbitfield mask )
{
	crStatePushAttrib( mask );
	cr_server.head_spu->dispatch_table.PushAttrib( mask );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPushMatrix( void )
{
	crStatePushMatrix(  );
	cr_server.head_spu->dispatch_table.PushMatrix(  );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchPushName( GLuint name )
{
	crStatePushName( name );
	cr_server.head_spu->dispatch_table.PushName( name );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos2d( GLdouble x, GLdouble y )
{
	crStateRasterPos2d( x, y );
	cr_server.head_spu->dispatch_table.RasterPos2d( x, y );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos2dv( const GLdouble *v )
{
	crStateRasterPos2dv( v );
	cr_server.head_spu->dispatch_table.RasterPos2dv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos2f( GLfloat x, GLfloat y )
{
	crStateRasterPos2f( x, y );
	cr_server.head_spu->dispatch_table.RasterPos2f( x, y );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos2fv( const GLfloat *v )
{
	crStateRasterPos2fv( v );
	cr_server.head_spu->dispatch_table.RasterPos2fv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos2i( GLint x, GLint y )
{
	crStateRasterPos2i( x, y );
	cr_server.head_spu->dispatch_table.RasterPos2i( x, y );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos2iv( const GLint *v )
{
	crStateRasterPos2iv( v );
	cr_server.head_spu->dispatch_table.RasterPos2iv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos2s( GLshort x, GLshort y )
{
	crStateRasterPos2s( x, y );
	cr_server.head_spu->dispatch_table.RasterPos2s( x, y );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos2sv( const GLshort *v )
{
	crStateRasterPos2sv( v );
	cr_server.head_spu->dispatch_table.RasterPos2sv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos3d( GLdouble x, GLdouble y, GLdouble z )
{
	crStateRasterPos3d( x, y, z );
	cr_server.head_spu->dispatch_table.RasterPos3d( x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos3dv( const GLdouble *v )
{
	crStateRasterPos3dv( v );
	cr_server.head_spu->dispatch_table.RasterPos3dv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos3f( GLfloat x, GLfloat y, GLfloat z )
{
	crStateRasterPos3f( x, y, z );
	cr_server.head_spu->dispatch_table.RasterPos3f( x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos3fv( const GLfloat *v )
{
	crStateRasterPos3fv( v );
	cr_server.head_spu->dispatch_table.RasterPos3fv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos3i( GLint x, GLint y, GLint z )
{
	crStateRasterPos3i( x, y, z );
	cr_server.head_spu->dispatch_table.RasterPos3i( x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos3iv( const GLint *v )
{
	crStateRasterPos3iv( v );
	cr_server.head_spu->dispatch_table.RasterPos3iv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos3s( GLshort x, GLshort y, GLshort z )
{
	crStateRasterPos3s( x, y, z );
	cr_server.head_spu->dispatch_table.RasterPos3s( x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos3sv( const GLshort *v )
{
	crStateRasterPos3sv( v );
	cr_server.head_spu->dispatch_table.RasterPos3sv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w )
{
	crStateRasterPos4d( x, y, z, w );
	cr_server.head_spu->dispatch_table.RasterPos4d( x, y, z, w );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos4dv( const GLdouble *v )
{
	crStateRasterPos4dv( v );
	cr_server.head_spu->dispatch_table.RasterPos4dv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w )
{
	crStateRasterPos4f( x, y, z, w );
	cr_server.head_spu->dispatch_table.RasterPos4f( x, y, z, w );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos4fv( const GLfloat *v )
{
	crStateRasterPos4fv( v );
	cr_server.head_spu->dispatch_table.RasterPos4fv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos4i( GLint x, GLint y, GLint z, GLint w )
{
	crStateRasterPos4i( x, y, z, w );
	cr_server.head_spu->dispatch_table.RasterPos4i( x, y, z, w );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos4iv( const GLint *v )
{
	crStateRasterPos4iv( v );
	cr_server.head_spu->dispatch_table.RasterPos4iv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos4s( GLshort x, GLshort y, GLshort z, GLshort w )
{
	crStateRasterPos4s( x, y, z, w );
	cr_server.head_spu->dispatch_table.RasterPos4s( x, y, z, w );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRasterPos4sv( const GLshort *v )
{
	crStateRasterPos4sv( v );
	cr_server.head_spu->dispatch_table.RasterPos4sv( v );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchReadBuffer( GLenum mode )
{
	crStateReadBuffer( mode );
	cr_server.head_spu->dispatch_table.ReadBuffer( mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRotated( GLdouble angle, GLdouble x, GLdouble y, GLdouble z )
{
	crStateRotated( angle, x, y, z );
	cr_server.head_spu->dispatch_table.Rotated( angle, x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchRotatef( GLfloat angle, GLfloat x, GLfloat y, GLfloat z )
{
	crStateRotatef( angle, x, y, z );
	cr_server.head_spu->dispatch_table.Rotatef( angle, x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchScaled( GLdouble x, GLdouble y, GLdouble z )
{
	crStateScaled( x, y, z );
	cr_server.head_spu->dispatch_table.Scaled( x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchScalef( GLfloat x, GLfloat y, GLfloat z )
{
	crStateScalef( x, y, z );
	cr_server.head_spu->dispatch_table.Scalef( x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchScissor( GLint x, GLint y, GLsizei width, GLsizei height )
{
	crStateScissor( x, y, width, height );
	cr_server.head_spu->dispatch_table.Scissor( x, y, width, height );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColorPointerEXT( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer )
{
	crStateSecondaryColorPointerEXT( size, type, stride, pointer );
	cr_server.head_spu->dispatch_table.SecondaryColorPointerEXT( size, type, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchShadeModel( GLenum mode )
{
	crStateShadeModel( mode );
	cr_server.head_spu->dispatch_table.ShadeModel( mode );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchStencilFunc( GLenum func, GLint ref, GLuint mask )
{
	crStateStencilFunc( func, ref, mask );
	cr_server.head_spu->dispatch_table.StencilFunc( func, ref, mask );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchStencilMask( GLuint mask )
{
	crStateStencilMask( mask );
	cr_server.head_spu->dispatch_table.StencilMask( mask );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchStencilOp( GLenum fail, GLenum zfail, GLenum zpass )
{
	crStateStencilOp( fail, zfail, zpass );
	cr_server.head_spu->dispatch_table.StencilOp( fail, zfail, zpass );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoordPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer )
{
	crStateTexCoordPointer( size, type, stride, pointer );
	cr_server.head_spu->dispatch_table.TexCoordPointer( size, type, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexEnvf( GLenum target, GLenum pname, GLfloat param )
{
	crStateTexEnvf( target, pname, param );
	cr_server.head_spu->dispatch_table.TexEnvf( target, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexEnvfv( GLenum target, GLenum pname, const GLfloat *params )
{
	crStateTexEnvfv( target, pname, params );
	cr_server.head_spu->dispatch_table.TexEnvfv( target, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexEnvi( GLenum target, GLenum pname, GLint param )
{
	crStateTexEnvi( target, pname, param );
	cr_server.head_spu->dispatch_table.TexEnvi( target, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexEnviv( GLenum target, GLenum pname, const GLint *params )
{
	crStateTexEnviv( target, pname, params );
	cr_server.head_spu->dispatch_table.TexEnviv( target, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexGend( GLenum coord, GLenum pname, GLdouble param )
{
	crStateTexGend( coord, pname, param );
	cr_server.head_spu->dispatch_table.TexGend( coord, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexGendv( GLenum coord, GLenum pname, const GLdouble *params )
{
	crStateTexGendv( coord, pname, params );
	cr_server.head_spu->dispatch_table.TexGendv( coord, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexGenf( GLenum coord, GLenum pname, GLfloat param )
{
	crStateTexGenf( coord, pname, param );
	cr_server.head_spu->dispatch_table.TexGenf( coord, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexGenfv( GLenum coord, GLenum pname, const GLfloat *params )
{
	crStateTexGenfv( coord, pname, params );
	cr_server.head_spu->dispatch_table.TexGenfv( coord, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexGeni( GLenum coord, GLenum pname, GLint param )
{
	crStateTexGeni( coord, pname, param );
	cr_server.head_spu->dispatch_table.TexGeni( coord, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexGeniv( GLenum coord, GLenum pname, const GLint *params )
{
	crStateTexGeniv( coord, pname, params );
	cr_server.head_spu->dispatch_table.TexGeniv( coord, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexImage1D( GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels )
{
	crStateTexImage1D( target, level, internalformat, width, border, format, type, pixels );
	cr_server.head_spu->dispatch_table.TexImage1D( target, level, internalformat, width, border, format, type, pixels );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexImage2D( GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels )
{
	crStateTexImage2D( target, level, internalformat, width, height, border, format, type, pixels );
	cr_server.head_spu->dispatch_table.TexImage2D( target, level, internalformat, width, height, border, format, type, pixels );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexImage3D( GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels )
{
	crStateTexImage3D( target, level, internalformat, width, height, depth, border, format, type, pixels );
	cr_server.head_spu->dispatch_table.TexImage3D( target, level, internalformat, width, height, depth, border, format, type, pixels );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexImage3DEXT( GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels )
{
	crStateTexImage3DEXT( target, level, internalFormat, width, height, depth, border, format, type, pixels );
	cr_server.head_spu->dispatch_table.TexImage3DEXT( target, level, internalFormat, width, height, depth, border, format, type, pixels );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexParameterf( GLenum target, GLenum pname, GLfloat param )
{
	crStateTexParameterf( target, pname, param );
	cr_server.head_spu->dispatch_table.TexParameterf( target, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexParameterfv( GLenum target, GLenum pname, const GLfloat *params )
{
	crStateTexParameterfv( target, pname, params );
	cr_server.head_spu->dispatch_table.TexParameterfv( target, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexParameteri( GLenum target, GLenum pname, GLint param )
{
	crStateTexParameteri( target, pname, param );
	cr_server.head_spu->dispatch_table.TexParameteri( target, pname, param );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexParameteriv( GLenum target, GLenum pname, const GLint *params )
{
	crStateTexParameteriv( target, pname, params );
	cr_server.head_spu->dispatch_table.TexParameteriv( target, pname, params );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels )
{
	crStateTexSubImage1D( target, level, xoffset, width, format, type, pixels );
	cr_server.head_spu->dispatch_table.TexSubImage1D( target, level, xoffset, width, format, type, pixels );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels )
{
	crStateTexSubImage2D( target, level, xoffset, yoffset, width, height, format, type, pixels );
	cr_server.head_spu->dispatch_table.TexSubImage2D( target, level, xoffset, yoffset, width, height, format, type, pixels );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTexSubImage3D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels )
{
	crStateTexSubImage3D( target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels );
	cr_server.head_spu->dispatch_table.TexSubImage3D( target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTranslated( GLdouble x, GLdouble y, GLdouble z )
{
	crStateTranslated( x, y, z );
	cr_server.head_spu->dispatch_table.Translated( x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchTranslatef( GLfloat x, GLfloat y, GLfloat z )
{
	crStateTranslatef( x, y, z );
	cr_server.head_spu->dispatch_table.Translatef( x, y, z );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchVertexAttribPointerNV( GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer )
{
	crStateVertexAttribPointerNV( index, size, type, stride, pointer );
	cr_server.head_spu->dispatch_table.VertexAttribPointerNV( index, size, type, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchVertexPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer )
{
	crStateVertexPointer( size, type, stride, pointer );
	cr_server.head_spu->dispatch_table.VertexPointer( size, type, stride, pointer );
}
void SERVER_DISPATCH_APIENTRY crServerDispatchColor3b( GLbyte red, GLbyte green, GLbyte blue )
{
	cr_server.head_spu->dispatch_table.Color3b( red, green, blue );
	cr_server.current.color.b3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor3d( GLdouble red, GLdouble green, GLdouble blue )
{
	cr_server.head_spu->dispatch_table.Color3d( red, green, blue );
	cr_server.current.color.d3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor3f( GLfloat red, GLfloat green, GLfloat blue )
{
	cr_server.head_spu->dispatch_table.Color3f( red, green, blue );
	cr_server.current.color.f3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor3i( GLint red, GLint green, GLint blue )
{
	cr_server.head_spu->dispatch_table.Color3i( red, green, blue );
	cr_server.current.color.i3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor3s( GLshort red, GLshort green, GLshort blue )
{
	cr_server.head_spu->dispatch_table.Color3s( red, green, blue );
	cr_server.current.color.s3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor3ub( GLubyte red, GLubyte green, GLubyte blue )
{
	cr_server.head_spu->dispatch_table.Color3ub( red, green, blue );
	cr_server.current.color.ub3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor3ui( GLuint red, GLuint green, GLuint blue )
{
	cr_server.head_spu->dispatch_table.Color3ui( red, green, blue );
	cr_server.current.color.ui3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor3us( GLushort red, GLushort green, GLushort blue )
{
	cr_server.head_spu->dispatch_table.Color3us( red, green, blue );
	cr_server.current.color.us3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor4b( GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha )
{
	cr_server.head_spu->dispatch_table.Color4b( red, green, blue, alpha );
	cr_server.current.color.b4 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor4d( GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha )
{
	cr_server.head_spu->dispatch_table.Color4d( red, green, blue, alpha );
	cr_server.current.color.d4 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor4f( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha )
{
	cr_server.head_spu->dispatch_table.Color4f( red, green, blue, alpha );
	cr_server.current.color.f4 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor4i( GLint red, GLint green, GLint blue, GLint alpha )
{
	cr_server.head_spu->dispatch_table.Color4i( red, green, blue, alpha );
	cr_server.current.color.i4 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor4s( GLshort red, GLshort green, GLshort blue, GLshort alpha )
{
	cr_server.head_spu->dispatch_table.Color4s( red, green, blue, alpha );
	cr_server.current.color.s4 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor4ub( GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha )
{
	cr_server.head_spu->dispatch_table.Color4ub( red, green, blue, alpha );
	cr_server.current.color.ub4 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor4ui( GLuint red, GLuint green, GLuint blue, GLuint alpha )
{
	cr_server.head_spu->dispatch_table.Color4ui( red, green, blue, alpha );
	cr_server.current.color.ui4 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchColor4us( GLushort red, GLushort green, GLushort blue, GLushort alpha )
{
	cr_server.head_spu->dispatch_table.Color4us( red, green, blue, alpha );
	cr_server.current.color.us4 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchEdgeFlag( GLboolean flag )
{
	cr_server.head_spu->dispatch_table.EdgeFlag( flag );
	cr_server.current.edgeFlag.l1 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchIndexd( GLdouble c )
{
	cr_server.head_spu->dispatch_table.Indexd( c );
	cr_server.current.index.d1 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchIndexf( GLfloat c )
{
	cr_server.head_spu->dispatch_table.Indexf( c );
	cr_server.current.index.f1 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchIndexi( GLint c )
{
	cr_server.head_spu->dispatch_table.Indexi( c );
	cr_server.current.index.i1 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchIndexs( GLshort c )
{
	cr_server.head_spu->dispatch_table.Indexs( c );
	cr_server.current.index.s1 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchIndexub( GLubyte c )
{
	cr_server.head_spu->dispatch_table.Indexub( c );
	cr_server.current.index.ub1 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord1dARB( GLenum texture, GLdouble s )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord1dARB( texture, s );
	cr_server.current.texCoord.d1[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord1fARB( GLenum texture, GLfloat s )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord1fARB( texture, s );
	cr_server.current.texCoord.f1[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord1iARB( GLenum texture, GLint s )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord1iARB( texture, s );
	cr_server.current.texCoord.i1[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord1sARB( GLenum texture, GLshort s )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord1sARB( texture, s );
	cr_server.current.texCoord.s1[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord2dARB( GLenum texture, GLdouble s, GLdouble t )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord2dARB( texture, s, t );
	cr_server.current.texCoord.d2[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord2fARB( GLenum texture, GLfloat s, GLfloat t )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord2fARB( texture, s, t );
	cr_server.current.texCoord.f2[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord2iARB( GLenum texture, GLint s, GLint t )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord2iARB( texture, s, t );
	cr_server.current.texCoord.i2[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord2sARB( GLenum texture, GLshort s, GLshort t )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord2sARB( texture, s, t );
	cr_server.current.texCoord.s2[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord3dARB( GLenum texture, GLdouble s, GLdouble t, GLdouble r )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord3dARB( texture, s, t, r );
	cr_server.current.texCoord.d3[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord3fARB( GLenum texture, GLfloat s, GLfloat t, GLfloat r )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord3fARB( texture, s, t, r );
	cr_server.current.texCoord.f3[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord3iARB( GLenum texture, GLint s, GLint t, GLint r )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord3iARB( texture, s, t, r );
	cr_server.current.texCoord.i3[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord3sARB( GLenum texture, GLshort s, GLshort t, GLshort r )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord3sARB( texture, s, t, r );
	cr_server.current.texCoord.s3[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord4dARB( GLenum texture, GLdouble s, GLdouble t, GLdouble r, GLdouble q )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord4dARB( texture, s, t, r, q );
	cr_server.current.texCoord.d4[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord4fARB( GLenum texture, GLfloat s, GLfloat t, GLfloat r, GLfloat q )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord4fARB( texture, s, t, r, q );
	cr_server.current.texCoord.f4[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord4iARB( GLenum texture, GLint s, GLint t, GLint r, GLint q )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord4iARB( texture, s, t, r, q );
	cr_server.current.texCoord.i4[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchMultiTexCoord4sARB( GLenum texture, GLshort s, GLshort t, GLshort r, GLshort q )
{
	cr_server.head_spu->dispatch_table.MultiTexCoord4sARB( texture, s, t, r, q );
	cr_server.current.texCoord.s4[texture-GL_TEXTURE0_ARB] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchNormal3b( GLbyte nx, GLbyte ny, GLbyte nz )
{
	cr_server.head_spu->dispatch_table.Normal3b( nx, ny, nz );
	cr_server.current.normal.b3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchNormal3d( GLdouble nx, GLdouble ny, GLdouble nz )
{
	cr_server.head_spu->dispatch_table.Normal3d( nx, ny, nz );
	cr_server.current.normal.d3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchNormal3f( GLfloat nx, GLfloat ny, GLfloat nz )
{
	cr_server.head_spu->dispatch_table.Normal3f( nx, ny, nz );
	cr_server.current.normal.f3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchNormal3i( GLint nx, GLint ny, GLint nz )
{
	cr_server.head_spu->dispatch_table.Normal3i( nx, ny, nz );
	cr_server.current.normal.i3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchNormal3s( GLshort nx, GLshort ny, GLshort nz )
{
	cr_server.head_spu->dispatch_table.Normal3s( nx, ny, nz );
	cr_server.current.normal.s3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColor3bEXT( GLbyte red, GLbyte green, GLbyte blue )
{
	cr_server.head_spu->dispatch_table.SecondaryColor3bEXT( red, green, blue );
	cr_server.current.secondaryColor.b3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColor3dEXT( GLdouble red, GLdouble green, GLdouble blue )
{
	cr_server.head_spu->dispatch_table.SecondaryColor3dEXT( red, green, blue );
	cr_server.current.secondaryColor.d3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColor3fEXT( GLfloat red, GLfloat green, GLfloat blue )
{
	cr_server.head_spu->dispatch_table.SecondaryColor3fEXT( red, green, blue );
	cr_server.current.secondaryColor.f3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColor3iEXT( GLint red, GLint green, GLint blue )
{
	cr_server.head_spu->dispatch_table.SecondaryColor3iEXT( red, green, blue );
	cr_server.current.secondaryColor.i3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColor3sEXT( GLshort red, GLshort green, GLshort blue )
{
	cr_server.head_spu->dispatch_table.SecondaryColor3sEXT( red, green, blue );
	cr_server.current.secondaryColor.s3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColor3ubEXT( GLubyte red, GLubyte green, GLubyte blue )
{
	cr_server.head_spu->dispatch_table.SecondaryColor3ubEXT( red, green, blue );
	cr_server.current.secondaryColor.ub3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColor3uiEXT( GLuint red, GLuint green, GLuint blue )
{
	cr_server.head_spu->dispatch_table.SecondaryColor3uiEXT( red, green, blue );
	cr_server.current.secondaryColor.ui3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchSecondaryColor3usEXT( GLushort red, GLushort green, GLushort blue )
{
	cr_server.head_spu->dispatch_table.SecondaryColor3usEXT( red, green, blue );
	cr_server.current.secondaryColor.us3 = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord1d( GLdouble s )
{
	cr_server.head_spu->dispatch_table.TexCoord1d( s );
	cr_server.current.texCoord.d1[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord1f( GLfloat s )
{
	cr_server.head_spu->dispatch_table.TexCoord1f( s );
	cr_server.current.texCoord.f1[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord1i( GLint s )
{
	cr_server.head_spu->dispatch_table.TexCoord1i( s );
	cr_server.current.texCoord.i1[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord1s( GLshort s )
{
	cr_server.head_spu->dispatch_table.TexCoord1s( s );
	cr_server.current.texCoord.s1[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord2d( GLdouble s, GLdouble t )
{
	cr_server.head_spu->dispatch_table.TexCoord2d( s, t );
	cr_server.current.texCoord.d2[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord2f( GLfloat s, GLfloat t )
{
	cr_server.head_spu->dispatch_table.TexCoord2f( s, t );
	cr_server.current.texCoord.f2[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord2i( GLint s, GLint t )
{
	cr_server.head_spu->dispatch_table.TexCoord2i( s, t );
	cr_server.current.texCoord.i2[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord2s( GLshort s, GLshort t )
{
	cr_server.head_spu->dispatch_table.TexCoord2s( s, t );
	cr_server.current.texCoord.s2[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord3d( GLdouble s, GLdouble t, GLdouble r )
{
	cr_server.head_spu->dispatch_table.TexCoord3d( s, t, r );
	cr_server.current.texCoord.d3[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord3f( GLfloat s, GLfloat t, GLfloat r )
{
	cr_server.head_spu->dispatch_table.TexCoord3f( s, t, r );
	cr_server.current.texCoord.f3[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord3i( GLint s, GLint t, GLint r )
{
	cr_server.head_spu->dispatch_table.TexCoord3i( s, t, r );
	cr_server.current.texCoord.i3[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord3s( GLshort s, GLshort t, GLshort r )
{
	cr_server.head_spu->dispatch_table.TexCoord3s( s, t, r );
	cr_server.current.texCoord.s3[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord4d( GLdouble s, GLdouble t, GLdouble r, GLdouble q )
{
	cr_server.head_spu->dispatch_table.TexCoord4d( s, t, r, q );
	cr_server.current.texCoord.d4[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord4f( GLfloat s, GLfloat t, GLfloat r, GLfloat q )
{
	cr_server.head_spu->dispatch_table.TexCoord4f( s, t, r, q );
	cr_server.current.texCoord.f4[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord4i( GLint s, GLint t, GLint r, GLint q )
{
	cr_server.head_spu->dispatch_table.TexCoord4i( s, t, r, q );
	cr_server.current.texCoord.i4[0] = cr_unpackData;
}

void SERVER_DISPATCH_APIENTRY crServerDispatchTexCoord4s( GLshort s, GLshort t, GLshort r, GLshort q )
{
	cr_server.head_spu->dispatch_table.TexCoord4s( s, t, r, q );
	cr_server.current.texCoord.s4[0] = cr_unpackData;
}


void crServerInitDispatch(void)
{
	crSPUInitDispatchTable( &(cr_server.dispatch) );
	crSPUCopyDispatchTable( &(cr_server.dispatch), &(cr_server.head_spu->dispatch_table ) );

	cr_server.dispatch.ActiveTextureARB = crServerDispatchActiveTextureARB;
	cr_server.dispatch.AlphaFunc = crServerDispatchAlphaFunc;
	cr_server.dispatch.AreProgramsResidentNV = crServerDispatchAreProgramsResidentNV;
	cr_server.dispatch.AreTexturesResident = crServerDispatchAreTexturesResident;
	cr_server.dispatch.BarrierCreateCR = crServerDispatchBarrierCreateCR;
	cr_server.dispatch.BarrierExecCR = crServerDispatchBarrierExecCR;
	cr_server.dispatch.Begin = crServerDispatchBegin;
	cr_server.dispatch.BindTexture = crServerDispatchBindTexture;
	cr_server.dispatch.Bitmap = crServerDispatchBitmap;
	cr_server.dispatch.BlendColorEXT = crServerDispatchBlendColorEXT;
	cr_server.dispatch.BlendFunc = crServerDispatchBlendFunc;
	cr_server.dispatch.BoundsInfoCR = crServerDispatchBoundsInfoCR;
	cr_server.dispatch.ChromiumParametervCR = crServerDispatchChromiumParametervCR;
	cr_server.dispatch.Clear = crServerDispatchClear;
	cr_server.dispatch.ClearAccum = crServerDispatchClearAccum;
	cr_server.dispatch.ClearColor = crServerDispatchClearColor;
	cr_server.dispatch.ClearDepth = crServerDispatchClearDepth;
	cr_server.dispatch.ClearIndex = crServerDispatchClearIndex;
	cr_server.dispatch.ClearStencil = crServerDispatchClearStencil;
	cr_server.dispatch.ClientActiveTextureARB = crServerDispatchClientActiveTextureARB;
	cr_server.dispatch.ClipPlane = crServerDispatchClipPlane;
	cr_server.dispatch.Color3b = crServerDispatchColor3b;
	cr_server.dispatch.Color3d = crServerDispatchColor3d;
	cr_server.dispatch.Color3f = crServerDispatchColor3f;
	cr_server.dispatch.Color3fv = crServerDispatchColor3fv;
	cr_server.dispatch.Color3i = crServerDispatchColor3i;
	cr_server.dispatch.Color3s = crServerDispatchColor3s;
	cr_server.dispatch.Color3ub = crServerDispatchColor3ub;
	cr_server.dispatch.Color3ui = crServerDispatchColor3ui;
	cr_server.dispatch.Color3us = crServerDispatchColor3us;
	cr_server.dispatch.Color4b = crServerDispatchColor4b;
	cr_server.dispatch.Color4d = crServerDispatchColor4d;
	cr_server.dispatch.Color4f = crServerDispatchColor4f;
	cr_server.dispatch.Color4fv = crServerDispatchColor4fv;
	cr_server.dispatch.Color4i = crServerDispatchColor4i;
	cr_server.dispatch.Color4s = crServerDispatchColor4s;
	cr_server.dispatch.Color4ub = crServerDispatchColor4ub;
	cr_server.dispatch.Color4ui = crServerDispatchColor4ui;
	cr_server.dispatch.Color4us = crServerDispatchColor4us;
	cr_server.dispatch.ColorMask = crServerDispatchColorMask;
	cr_server.dispatch.ColorMaterial = crServerDispatchColorMaterial;
	cr_server.dispatch.ColorPointer = crServerDispatchColorPointer;
	cr_server.dispatch.CombinerInputNV = crServerDispatchCombinerInputNV;
	cr_server.dispatch.CombinerOutputNV = crServerDispatchCombinerOutputNV;
	cr_server.dispatch.CombinerParameterfNV = crServerDispatchCombinerParameterfNV;
	cr_server.dispatch.CombinerParameterfvNV = crServerDispatchCombinerParameterfvNV;
	cr_server.dispatch.CombinerParameteriNV = crServerDispatchCombinerParameteriNV;
	cr_server.dispatch.CombinerParameterivNV = crServerDispatchCombinerParameterivNV;
	cr_server.dispatch.CombinerStageParameterfvNV = crServerDispatchCombinerStageParameterfvNV;
	cr_server.dispatch.CreateContext = crServerDispatchCreateContext;
	cr_server.dispatch.CullFace = crServerDispatchCullFace;
	cr_server.dispatch.DeleteLists = crServerDispatchDeleteLists;
	cr_server.dispatch.DeleteTextures = crServerDispatchDeleteTextures;
	cr_server.dispatch.DepthFunc = crServerDispatchDepthFunc;
	cr_server.dispatch.DepthMask = crServerDispatchDepthMask;
	cr_server.dispatch.DepthRange = crServerDispatchDepthRange;
	cr_server.dispatch.DestroyContext = crServerDispatchDestroyContext;
	cr_server.dispatch.Disable = crServerDispatchDisable;
	cr_server.dispatch.DisableClientState = crServerDispatchDisableClientState;
	cr_server.dispatch.DrawBuffer = crServerDispatchDrawBuffer;
	cr_server.dispatch.EdgeFlag = crServerDispatchEdgeFlag;
	cr_server.dispatch.EdgeFlagPointer = crServerDispatchEdgeFlagPointer;
	cr_server.dispatch.Enable = crServerDispatchEnable;
	cr_server.dispatch.EnableClientState = crServerDispatchEnableClientState;
	cr_server.dispatch.End = crServerDispatchEnd;
	cr_server.dispatch.EndList = crServerDispatchEndList;
	cr_server.dispatch.FeedbackBuffer = crServerDispatchFeedbackBuffer;
	cr_server.dispatch.FinalCombinerInputNV = crServerDispatchFinalCombinerInputNV;
	cr_server.dispatch.FogCoordPointerEXT = crServerDispatchFogCoordPointerEXT;
	cr_server.dispatch.Fogf = crServerDispatchFogf;
	cr_server.dispatch.Fogfv = crServerDispatchFogfv;
	cr_server.dispatch.Fogi = crServerDispatchFogi;
	cr_server.dispatch.Fogiv = crServerDispatchFogiv;
	cr_server.dispatch.FrontFace = crServerDispatchFrontFace;
	cr_server.dispatch.Frustum = crServerDispatchFrustum;
	cr_server.dispatch.GenFencesNV = crServerDispatchGenFencesNV;
	cr_server.dispatch.GenLists = crServerDispatchGenLists;
	cr_server.dispatch.GenProgramsNV = crServerDispatchGenProgramsNV;
	cr_server.dispatch.GenTextures = crServerDispatchGenTextures;
	cr_server.dispatch.GetBooleanv = crServerDispatchGetBooleanv;
	cr_server.dispatch.GetChromiumParametervCR = crServerDispatchGetChromiumParametervCR;
	cr_server.dispatch.GetClipPlane = crServerDispatchGetClipPlane;
	cr_server.dispatch.GetCombinerInputParameterfvNV = crServerDispatchGetCombinerInputParameterfvNV;
	cr_server.dispatch.GetCombinerInputParameterivNV = crServerDispatchGetCombinerInputParameterivNV;
	cr_server.dispatch.GetCombinerOutputParameterfvNV = crServerDispatchGetCombinerOutputParameterfvNV;
	cr_server.dispatch.GetCombinerOutputParameterivNV = crServerDispatchGetCombinerOutputParameterivNV;
	cr_server.dispatch.GetCombinerStageParameterfvNV = crServerDispatchGetCombinerStageParameterfvNV;
	cr_server.dispatch.GetDoublev = crServerDispatchGetDoublev;
	cr_server.dispatch.GetError = crServerDispatchGetError;
	cr_server.dispatch.GetFenceivNV = crServerDispatchGetFenceivNV;
	cr_server.dispatch.GetFinalCombinerInputParameterfvNV = crServerDispatchGetFinalCombinerInputParameterfvNV;
	cr_server.dispatch.GetFinalCombinerInputParameterivNV = crServerDispatchGetFinalCombinerInputParameterivNV;
	cr_server.dispatch.GetFloatv = crServerDispatchGetFloatv;
	cr_server.dispatch.GetIntegerv = crServerDispatchGetIntegerv;
	cr_server.dispatch.GetLightfv = crServerDispatchGetLightfv;
	cr_server.dispatch.GetLightiv = crServerDispatchGetLightiv;
	cr_server.dispatch.GetMapdv = crServerDispatchGetMapdv;
	cr_server.dispatch.GetMapfv = crServerDispatchGetMapfv;
	cr_server.dispatch.GetMapiv = crServerDispatchGetMapiv;
	cr_server.dispatch.GetMaterialfv = crServerDispatchGetMaterialfv;
	cr_server.dispatch.GetMaterialiv = crServerDispatchGetMaterialiv;
	cr_server.dispatch.GetPixelMapfv = crServerDispatchGetPixelMapfv;
	cr_server.dispatch.GetPixelMapuiv = crServerDispatchGetPixelMapuiv;
	cr_server.dispatch.GetPixelMapusv = crServerDispatchGetPixelMapusv;
	cr_server.dispatch.GetPointerv = crServerDispatchGetPointerv;
	cr_server.dispatch.GetPolygonStipple = crServerDispatchGetPolygonStipple;
	cr_server.dispatch.GetProgramParameterdvNV = crServerDispatchGetProgramParameterdvNV;
	cr_server.dispatch.GetProgramParameterfvNV = crServerDispatchGetProgramParameterfvNV;
	cr_server.dispatch.GetProgramStringNV = crServerDispatchGetProgramStringNV;
	cr_server.dispatch.GetProgramivNV = crServerDispatchGetProgramivNV;
	cr_server.dispatch.GetString = crServerDispatchGetString;
	cr_server.dispatch.GetTexEnvfv = crServerDispatchGetTexEnvfv;
	cr_server.dispatch.GetTexEnviv = crServerDispatchGetTexEnviv;
	cr_server.dispatch.GetTexGendv = crServerDispatchGetTexGendv;
	cr_server.dispatch.GetTexGenfv = crServerDispatchGetTexGenfv;
	cr_server.dispatch.GetTexGeniv = crServerDispatchGetTexGeniv;
	cr_server.dispatch.GetTexImage = crServerDispatchGetTexImage;
	cr_server.dispatch.GetTexLevelParameterfv = crServerDispatchGetTexLevelParameterfv;
	cr_server.dispatch.GetTexLevelParameteriv = crServerDispatchGetTexLevelParameteriv;
	cr_server.dispatch.GetTexParameterfv = crServerDispatchGetTexParameterfv;
	cr_server.dispatch.GetTexParameteriv = crServerDispatchGetTexParameteriv;
	cr_server.dispatch.GetTrackMatrixivNV = crServerDispatchGetTrackMatrixivNV;
	cr_server.dispatch.GetVertexAttribPointervNV = crServerDispatchGetVertexAttribPointervNV;
	cr_server.dispatch.GetVertexAttribdvNV = crServerDispatchGetVertexAttribdvNV;
	cr_server.dispatch.GetVertexAttribfvNV = crServerDispatchGetVertexAttribfvNV;
	cr_server.dispatch.GetVertexAttribivNV = crServerDispatchGetVertexAttribivNV;
	cr_server.dispatch.Hint = crServerDispatchHint;
	cr_server.dispatch.IndexMask = crServerDispatchIndexMask;
	cr_server.dispatch.IndexPointer = crServerDispatchIndexPointer;
	cr_server.dispatch.Indexd = crServerDispatchIndexd;
	cr_server.dispatch.Indexf = crServerDispatchIndexf;
	cr_server.dispatch.Indexi = crServerDispatchIndexi;
	cr_server.dispatch.Indexs = crServerDispatchIndexs;
	cr_server.dispatch.InitNames = crServerDispatchInitNames;
	cr_server.dispatch.InterleavedArrays = crServerDispatchInterleavedArrays;
	cr_server.dispatch.IsEnabled = crServerDispatchIsEnabled;
	cr_server.dispatch.IsFenceNV = crServerDispatchIsFenceNV;
	cr_server.dispatch.IsList = crServerDispatchIsList;
	cr_server.dispatch.IsProgramNV = crServerDispatchIsProgramNV;
	cr_server.dispatch.IsTexture = crServerDispatchIsTexture;
	cr_server.dispatch.LightModelf = crServerDispatchLightModelf;
	cr_server.dispatch.LightModelfv = crServerDispatchLightModelfv;
	cr_server.dispatch.LightModeli = crServerDispatchLightModeli;
	cr_server.dispatch.LightModeliv = crServerDispatchLightModeliv;
	cr_server.dispatch.Lightf = crServerDispatchLightf;
	cr_server.dispatch.Lightfv = crServerDispatchLightfv;
	cr_server.dispatch.Lighti = crServerDispatchLighti;
	cr_server.dispatch.Lightiv = crServerDispatchLightiv;
	cr_server.dispatch.LineStipple = crServerDispatchLineStipple;
	cr_server.dispatch.LineWidth = crServerDispatchLineWidth;
	cr_server.dispatch.ListBase = crServerDispatchListBase;
	cr_server.dispatch.LoadIdentity = crServerDispatchLoadIdentity;
	cr_server.dispatch.LoadMatrixd = crServerDispatchLoadMatrixd;
	cr_server.dispatch.LoadMatrixf = crServerDispatchLoadMatrixf;
	cr_server.dispatch.LoadName = crServerDispatchLoadName;
	cr_server.dispatch.LoadTransposeMatrixdARB = crServerDispatchLoadTransposeMatrixdARB;
	cr_server.dispatch.LoadTransposeMatrixfARB = crServerDispatchLoadTransposeMatrixfARB;
	cr_server.dispatch.LogicOp = crServerDispatchLogicOp;
	cr_server.dispatch.MakeCurrent = crServerDispatchMakeCurrent;
	cr_server.dispatch.Map1d = crServerDispatchMap1d;
	cr_server.dispatch.Map1f = crServerDispatchMap1f;
	cr_server.dispatch.Map2d = crServerDispatchMap2d;
	cr_server.dispatch.Map2f = crServerDispatchMap2f;
	cr_server.dispatch.MapGrid1d = crServerDispatchMapGrid1d;
	cr_server.dispatch.MapGrid1f = crServerDispatchMapGrid1f;
	cr_server.dispatch.MapGrid2d = crServerDispatchMapGrid2d;
	cr_server.dispatch.MapGrid2f = crServerDispatchMapGrid2f;
	cr_server.dispatch.Materialf = crServerDispatchMaterialf;
	cr_server.dispatch.Materialfv = crServerDispatchMaterialfv;
	cr_server.dispatch.Materiali = crServerDispatchMateriali;
	cr_server.dispatch.Materialiv = crServerDispatchMaterialiv;
	cr_server.dispatch.MatrixMode = crServerDispatchMatrixMode;
	cr_server.dispatch.MultMatrixd = crServerDispatchMultMatrixd;
	cr_server.dispatch.MultMatrixf = crServerDispatchMultMatrixf;
	cr_server.dispatch.MultTransposeMatrixdARB = crServerDispatchMultTransposeMatrixdARB;
	cr_server.dispatch.MultTransposeMatrixfARB = crServerDispatchMultTransposeMatrixfARB;
	cr_server.dispatch.NewList = crServerDispatchNewList;
	cr_server.dispatch.Normal3b = crServerDispatchNormal3b;
	cr_server.dispatch.Normal3d = crServerDispatchNormal3d;
	cr_server.dispatch.Normal3f = crServerDispatchNormal3f;
	cr_server.dispatch.Normal3i = crServerDispatchNormal3i;
	cr_server.dispatch.Normal3s = crServerDispatchNormal3s;
	cr_server.dispatch.NormalPointer = crServerDispatchNormalPointer;
	cr_server.dispatch.Ortho = crServerDispatchOrtho;
	cr_server.dispatch.PassThrough = crServerDispatchPassThrough;
	cr_server.dispatch.PixelMapfv = crServerDispatchPixelMapfv;
	cr_server.dispatch.PixelMapuiv = crServerDispatchPixelMapuiv;
	cr_server.dispatch.PixelMapusv = crServerDispatchPixelMapusv;
	cr_server.dispatch.PixelStoref = crServerDispatchPixelStoref;
	cr_server.dispatch.PixelStorei = crServerDispatchPixelStorei;
	cr_server.dispatch.PixelTransferf = crServerDispatchPixelTransferf;
	cr_server.dispatch.PixelTransferi = crServerDispatchPixelTransferi;
	cr_server.dispatch.PixelZoom = crServerDispatchPixelZoom;
	cr_server.dispatch.PointParameterfARB = crServerDispatchPointParameterfARB;
	cr_server.dispatch.PointParameterfvARB = crServerDispatchPointParameterfvARB;
	cr_server.dispatch.PointSize = crServerDispatchPointSize;
	cr_server.dispatch.PolygonMode = crServerDispatchPolygonMode;
	cr_server.dispatch.PolygonOffset = crServerDispatchPolygonOffset;
	cr_server.dispatch.PolygonStipple = crServerDispatchPolygonStipple;
	cr_server.dispatch.PopAttrib = crServerDispatchPopAttrib;
	cr_server.dispatch.PopMatrix = crServerDispatchPopMatrix;
	cr_server.dispatch.PopName = crServerDispatchPopName;
	cr_server.dispatch.PrioritizeTextures = crServerDispatchPrioritizeTextures;
	cr_server.dispatch.PushAttrib = crServerDispatchPushAttrib;
	cr_server.dispatch.PushMatrix = crServerDispatchPushMatrix;
	cr_server.dispatch.PushName = crServerDispatchPushName;
	cr_server.dispatch.RasterPos2d = crServerDispatchRasterPos2d;
	cr_server.dispatch.RasterPos2dv = crServerDispatchRasterPos2dv;
	cr_server.dispatch.RasterPos2f = crServerDispatchRasterPos2f;
	cr_server.dispatch.RasterPos2fv = crServerDispatchRasterPos2fv;
	cr_server.dispatch.RasterPos2i = crServerDispatchRasterPos2i;
	cr_server.dispatch.RasterPos2iv = crServerDispatchRasterPos2iv;
	cr_server.dispatch.RasterPos2s = crServerDispatchRasterPos2s;
	cr_server.dispatch.RasterPos2sv = crServerDispatchRasterPos2sv;
	cr_server.dispatch.RasterPos3d = crServerDispatchRasterPos3d;
	cr_server.dispatch.RasterPos3dv = crServerDispatchRasterPos3dv;
	cr_server.dispatch.RasterPos3f = crServerDispatchRasterPos3f;
	cr_server.dispatch.RasterPos3fv = crServerDispatchRasterPos3fv;
	cr_server.dispatch.RasterPos3i = crServerDispatchRasterPos3i;
	cr_server.dispatch.RasterPos3iv = crServerDispatchRasterPos3iv;
	cr_server.dispatch.RasterPos3s = crServerDispatchRasterPos3s;
	cr_server.dispatch.RasterPos3sv = crServerDispatchRasterPos3sv;
	cr_server.dispatch.RasterPos4d = crServerDispatchRasterPos4d;
	cr_server.dispatch.RasterPos4dv = crServerDispatchRasterPos4dv;
	cr_server.dispatch.RasterPos4f = crServerDispatchRasterPos4f;
	cr_server.dispatch.RasterPos4fv = crServerDispatchRasterPos4fv;
	cr_server.dispatch.RasterPos4i = crServerDispatchRasterPos4i;
	cr_server.dispatch.RasterPos4iv = crServerDispatchRasterPos4iv;
	cr_server.dispatch.RasterPos4s = crServerDispatchRasterPos4s;
	cr_server.dispatch.RasterPos4sv = crServerDispatchRasterPos4sv;
	cr_server.dispatch.ReadBuffer = crServerDispatchReadBuffer;
	cr_server.dispatch.ReadPixels = crServerDispatchReadPixels;
	cr_server.dispatch.RenderMode = crServerDispatchRenderMode;
	cr_server.dispatch.Rotated = crServerDispatchRotated;
	cr_server.dispatch.Rotatef = crServerDispatchRotatef;
	cr_server.dispatch.Scaled = crServerDispatchScaled;
	cr_server.dispatch.Scalef = crServerDispatchScalef;
	cr_server.dispatch.Scissor = crServerDispatchScissor;
	cr_server.dispatch.SecondaryColor3bEXT = crServerDispatchSecondaryColor3bEXT;
	cr_server.dispatch.SecondaryColor3dEXT = crServerDispatchSecondaryColor3dEXT;
	cr_server.dispatch.SecondaryColor3fEXT = crServerDispatchSecondaryColor3fEXT;
	cr_server.dispatch.SecondaryColor3iEXT = crServerDispatchSecondaryColor3iEXT;
	cr_server.dispatch.SecondaryColor3sEXT = crServerDispatchSecondaryColor3sEXT;
	cr_server.dispatch.SecondaryColor3ubEXT = crServerDispatchSecondaryColor3ubEXT;
	cr_server.dispatch.SecondaryColor3uiEXT = crServerDispatchSecondaryColor3uiEXT;
	cr_server.dispatch.SecondaryColor3usEXT = crServerDispatchSecondaryColor3usEXT;
	cr_server.dispatch.SecondaryColorPointerEXT = crServerDispatchSecondaryColorPointerEXT;
	cr_server.dispatch.SelectBuffer = crServerDispatchSelectBuffer;
	cr_server.dispatch.SemaphoreCreateCR = crServerDispatchSemaphoreCreateCR;
	cr_server.dispatch.SemaphorePCR = crServerDispatchSemaphorePCR;
	cr_server.dispatch.SemaphoreVCR = crServerDispatchSemaphoreVCR;
	cr_server.dispatch.ShadeModel = crServerDispatchShadeModel;
	cr_server.dispatch.StencilFunc = crServerDispatchStencilFunc;
	cr_server.dispatch.StencilMask = crServerDispatchStencilMask;
	cr_server.dispatch.StencilOp = crServerDispatchStencilOp;
	cr_server.dispatch.SwapBuffers = crServerDispatchSwapBuffers;
	cr_server.dispatch.TestFenceNV = crServerDispatchTestFenceNV;
	cr_server.dispatch.TexCoord1d = crServerDispatchTexCoord1d;
	cr_server.dispatch.TexCoord1f = crServerDispatchTexCoord1f;
	cr_server.dispatch.TexCoord1i = crServerDispatchTexCoord1i;
	cr_server.dispatch.TexCoord1s = crServerDispatchTexCoord1s;
	cr_server.dispatch.TexCoord2d = crServerDispatchTexCoord2d;
	cr_server.dispatch.TexCoord2f = crServerDispatchTexCoord2f;
	cr_server.dispatch.TexCoord2i = crServerDispatchTexCoord2i;
	cr_server.dispatch.TexCoord2s = crServerDispatchTexCoord2s;
	cr_server.dispatch.TexCoord3d = crServerDispatchTexCoord3d;
	cr_server.dispatch.TexCoord3f = crServerDispatchTexCoord3f;
	cr_server.dispatch.TexCoord3i = crServerDispatchTexCoord3i;
	cr_server.dispatch.TexCoord3s = crServerDispatchTexCoord3s;
	cr_server.dispatch.TexCoord4d = crServerDispatchTexCoord4d;
	cr_server.dispatch.TexCoord4f = crServerDispatchTexCoord4f;
	cr_server.dispatch.TexCoord4i = crServerDispatchTexCoord4i;
	cr_server.dispatch.TexCoord4s = crServerDispatchTexCoord4s;
	cr_server.dispatch.TexCoordPointer = crServerDispatchTexCoordPointer;
	cr_server.dispatch.TexEnvf = crServerDispatchTexEnvf;
	cr_server.dispatch.TexEnvfv = crServerDispatchTexEnvfv;
	cr_server.dispatch.TexEnvi = crServerDispatchTexEnvi;
	cr_server.dispatch.TexEnviv = crServerDispatchTexEnviv;
	cr_server.dispatch.TexGend = crServerDispatchTexGend;
	cr_server.dispatch.TexGendv = crServerDispatchTexGendv;
	cr_server.dispatch.TexGenf = crServerDispatchTexGenf;
	cr_server.dispatch.TexGenfv = crServerDispatchTexGenfv;
	cr_server.dispatch.TexGeni = crServerDispatchTexGeni;
	cr_server.dispatch.TexGeniv = crServerDispatchTexGeniv;
	cr_server.dispatch.TexImage1D = crServerDispatchTexImage1D;
	cr_server.dispatch.TexImage2D = crServerDispatchTexImage2D;
	cr_server.dispatch.TexImage3D = crServerDispatchTexImage3D;
	cr_server.dispatch.TexImage3DEXT = crServerDispatchTexImage3DEXT;
	cr_server.dispatch.TexParameterf = crServerDispatchTexParameterf;
	cr_server.dispatch.TexParameterfv = crServerDispatchTexParameterfv;
	cr_server.dispatch.TexParameteri = crServerDispatchTexParameteri;
	cr_server.dispatch.TexParameteriv = crServerDispatchTexParameteriv;
	cr_server.dispatch.TexSubImage1D = crServerDispatchTexSubImage1D;
	cr_server.dispatch.TexSubImage2D = crServerDispatchTexSubImage2D;
	cr_server.dispatch.TexSubImage3D = crServerDispatchTexSubImage3D;
	cr_server.dispatch.Translated = crServerDispatchTranslated;
	cr_server.dispatch.Translatef = crServerDispatchTranslatef;
	cr_server.dispatch.VertexAttribPointerNV = crServerDispatchVertexAttribPointerNV;
	cr_server.dispatch.VertexPointer = crServerDispatchVertexPointer;
	cr_server.dispatch.Viewport = crServerDispatchViewport;
	cr_server.dispatch.WindowCreate = crServerDispatchWindowCreate;
	cr_server.dispatch.Writeback = crServerDispatchWriteback;
}
