/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	

/* DO NOT EDIT - THIS FILE AUTOMATICALLY GENERATED BY server_retval.py SCRIPT */
#include "cr_spu.h"
#include "chromium.h"
#include "cr_error.h"
#include "cr_mem.h"
#include "cr_net.h"
#include "server_dispatch.h"
#include "server.h"

#include <memory.h>

void crServerReturnValue( const void *payload, unsigned int payload_len )
{
	CRMessageReadback *rb;
	int msg_len = sizeof( *rb ) + payload_len;
	if (cr_server.curClient->conn->type == CR_FILE)
	{
		return;
	}
	rb = (CRMessageReadback *) crAlloc( msg_len );

	rb->header.type = CR_MESSAGE_READBACK;
	memcpy( &(rb->writeback_ptr), &(cr_server.writeback_ptr), sizeof( rb->writeback_ptr ) );
	memcpy( &(rb->readback_ptr), &(cr_server.return_ptr), sizeof( rb->readback_ptr ) );
	memcpy( rb+1, payload, payload_len );
	crNetSend( cr_server.curClient->conn, NULL, rb, msg_len );
	crFree( rb );
}

GLboolean SERVER_DISPATCH_APIENTRY crServerDispatchAreProgramsResidentNV( GLsizei n, const GLuint *ids, GLboolean *residences )
{
	GLboolean retval;
	retval = cr_server.head_spu->dispatch_table.AreProgramsResidentNV( n, ids, residences );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLboolean SERVER_DISPATCH_APIENTRY crServerDispatchAreTexturesResident( GLsizei n, const GLuint *textures, GLboolean *residences )
{
	GLboolean retval;
	retval = cr_server.head_spu->dispatch_table.AreTexturesResident( n, textures, residences );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLuint SERVER_DISPATCH_APIENTRY crServerDispatchGenLists( GLsizei range )
{
	GLuint retval;
	retval = cr_server.head_spu->dispatch_table.GenLists( range );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLenum SERVER_DISPATCH_APIENTRY crServerDispatchGetError( void )
{
	GLenum retval;
	retval = cr_server.head_spu->dispatch_table.GetError(  );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLboolean SERVER_DISPATCH_APIENTRY crServerDispatchIsEnabled( GLenum cap )
{
	GLboolean retval;
	retval = cr_server.head_spu->dispatch_table.IsEnabled( cap );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLboolean SERVER_DISPATCH_APIENTRY crServerDispatchIsFenceNV( GLuint fence )
{
	GLboolean retval;
	retval = cr_server.head_spu->dispatch_table.IsFenceNV( fence );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLboolean SERVER_DISPATCH_APIENTRY crServerDispatchIsList( GLuint list )
{
	GLboolean retval;
	retval = cr_server.head_spu->dispatch_table.IsList( list );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLboolean SERVER_DISPATCH_APIENTRY crServerDispatchIsProgramNV( GLuint id )
{
	GLboolean retval;
	retval = cr_server.head_spu->dispatch_table.IsProgramNV( id );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLboolean SERVER_DISPATCH_APIENTRY crServerDispatchIsTexture( GLuint texture )
{
	GLboolean retval;
	retval = cr_server.head_spu->dispatch_table.IsTexture( texture );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLint SERVER_DISPATCH_APIENTRY crServerDispatchRenderMode( GLenum mode )
{
	GLint retval;
	retval = cr_server.head_spu->dispatch_table.RenderMode( mode );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLboolean SERVER_DISPATCH_APIENTRY crServerDispatchTestFenceNV( GLuint fence )
{
	GLboolean retval;
	retval = cr_server.head_spu->dispatch_table.TestFenceNV( fence );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
GLint SERVER_DISPATCH_APIENTRY crServerDispatchWindowCreate( const char *dpyName, GLint visBits )
{
	GLint retval;
	retval = cr_server.head_spu->dispatch_table.WindowCreate( dpyName, visBits );
	crServerReturnValue( &retval, sizeof(retval) );
	return retval; /* WILL PROBABLY BE IGNORED */
}
